### ISSUE TITLE
LWT support

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#100]
We need to support and test LWT (lightweight transaction) queries - the ones that have conditions within them, e.g. `IF EXISTS`.
We also have a Scylla-specific optimization, which returns a flag when preparing a statement that this statement is a lightweight transaction. We can then reduce the number of paxos conflicts by trying to always send the requests of the same key to the same node, which is assumed to be the paxos coordinator.

We should also have tests for LWT queries.

**Comment by piodul** [comment]
More info about the LWT optimization which might be useful:

Here's a PR to gocql which adds support for it: https://github.com/scylladb/gocql/pull/49
Discussion in a gocql issue about this optimization: https://github.com/scylladb/gocql/issues/40
Commit in Scylla which provides support for it: https://github.com/scylladb/scylla/commit/6028588148c556151d764f2a987c276cb4a21eb0

**Comment by bwalter** [comment]
Currently still missing the "applied" flag when executing LWT requests. Is there anything planned for this or shall we look for a workaround?
