### ISSUE TITLE
Use empty `CollectionType<T>` instead of `Option<CollectionType<T>>`

### ISSUE THREAD

**Issue by Zk2u** [scylladb/scylla-rust-driver#1001]
While [ScyllaDB doesn’t distinguish between null and and empty set](https://opensource.docs.scylladb.com/stable/cql/types.html#sets), it’s not very ergonomic to represent these collections as `Option<CollectionType<T>>`. For example, an empty set in Scylla should be deserialised into an empty `HashSet<T>`, not a `None::<CollectionType<T>>`. 

This would be a breaking API change.

**Comment by wprzytula** [comment]
I'll include this functionality in the ongoing deserialization refactor, planned for release 0.14.

**Comment by wprzytula** [comment]
@617a7aa Please take a look at #1007. Please confirm that the behaviour showcased by the added test is in line with your expectations.

**Comment by 617a7aa** [comment]
ACK, looks good to me.
