### ISSUE TITLE
Question: is it expected that if a test(s) from testsuit fails, next testsuit won't be executed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla-rust-driver#1005]
The question about test flow: 
is it expected that if a test(s) from testsuit fails, next testsuit won't be executed.

Example:
There is the one test that always fails when run with driver version `v0.11.1` and it is expected. 
Total ran tests with version `v0.11.1` are **178**.
Total ran tests with version `v0.12.0` (that has no failed tests) are **484**.
![Screenshot from 2024-05-21 10-32-15](https://github.com/scylladb/scylla-rust-driver/assets/34435448/362cf5f0-8ef2-42dc-933e-433e1c96f72e)

But when I got failure with version `v0.12.0`, total tests became 181. 
And I see that the testsuit with failed test is last testsuit.

![Screenshot from 2024-05-21 10-31-47](https://github.com/scylladb/scylla-rust-driver/assets/34435448/50c2d149-57e5-4907-9647-b968fe20d2e7)
**Note**: failed test with version `v0.11.1` is excluded, so it is not reported failed test on this screenshot.

**Comment by mykaul** [comment]
@juliayakovlev - issue is not the optimal venue to ask questions.

**Comment by wprzytula** [comment]
The behaviour to not run any more testsuits once any test fails is the default in cargo (the _fail fast_ option) to accelerate TDD workflows (see https://github.com/rust-lang/cargo/issues/1904). For faster development (as well as faster CI's negative response) we prefer to have it turned on. If you prefer to run all testsuits in SCT unconditionally, you could [turn it off by passing `--no-fail-fast` to `cargo test` invocation](https://doc.rust-lang.org/cargo/commands/cargo-test.html#options).
