### ISSUE TITLE
Don't fail metadata fetch when encountering invalid peer

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/scylla-rust-driver#1023]
When the row in system.peers is invalid (e.g. has rpc_address == null) the driver will encounter an error when trying to convert the row into Rust struct and this error will cause whole metadata fetch to fail.
Such invalid rows may happen in Scylla (and judging by the code in other drivers - in Cassandra too) sometimes, but should be a transient condition.
The correct behavior would be to log info about invalid row and skip it. It seems that all other driver (at least the ones I checked - Python, Java 3/4, Go) behave in this way.
As long as Scylla send topology change event after a corresponding node is fully available (so its row is correct in system.peers) it should not prevent us from implementing https://github.com/scylladb/scylla-rust-driver/issues/1008

**Comment by vponomaryov** [comment]
Our latte stress command failed to start in multi-dc setup facing this problem with provided `preferred region` parameter:

```
[2m2024-07-28T09:14:31.177595Z[0m [33m WARN[0m [2mscylla::transport::topology[0m[2m:[0m \
  Initial metadata read failed, proceeding with metadata consisting only of the initial peer list and dummy tokens. \
    This might result in suboptimal performance and schema information not being available. [3merror[0m[2m=[0m\
      ProtocolError("system.peers or system.local has invalid column type")
info: Loading workload script /scylla-qa-internal/custom_d1/workload2/latte/custom_d1_workload2.rn...
[2m2024-07-28T09:14:31.180326Z[0m [33m WARN[0m [2mscylla::transport::load_balancing::default[0m[2m:[0m \
  Datacenter specified as the preferred one (us-east1-s1) does not exist!
info: Connecting to ["10.142.0.59", "10.142.0.121", "10.142.0.125", "10.142.0.131", "10.142.0.142", "10.142.0.154", "10.142.0.159", "10.142.0.160", "10.142.0.5"]... 
[2m2024-07-28T09:14:31.180348Z[0m [33m WARN[0m [2mscylla::transport::load_balancing::default[0m[2m:[0m \
  Datacenter specified as the preferred one (us-east1-s1) does not exist!
error: Cassandra error: Failed to execute query "SELECT cluster_name, release_version FROM system.local" with params []: \
  Protocol Error: Empty query plan - driver bug!
[2m2024-07-28T09:14:31.180354Z[0m [31mERROR[0m [2mscylla::transport::load_balancing::plan[0m[2m:[0m \
  Load balancing policy returned an empty plan! The query cannot be executed. Routing info: \
    RoutingInfo { consistency: LocalQuorum, serial_consistency: Some(LocalSerial), token: None, table: None, is_confirmed_lwt: false }
```

I expect that stress command doesn't failed on the `preferred` thing.

So, I see this bug as high priority to be fixed.

**Comment by Lorak-mmk** [comment]
Actually there already is an issue about this, from 2 years ago: https://github.com/scylladb/scylla-rust-driver/issues/235
