### ISSUE TITLE
Add retrieving replication strategy information from the cluster

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#107]
In order to implement token-aware policy, we need to know what's the replication strategy for given keyspace in order to know which nodes are responsible the data we're trying to read/write.

First part is to get result metadata from the response of a `PREPARED` request. That's already mostly done - look for `TableSpec` and `deser_table_spec` for details.

Once we have the keyspace name (which is just a string), we can retrieve its replication strategy by selecting it from a system table: 
```cql
SELECT replication FROM system_schema.keyspaces WHERE keyspace_name = 'our_name';
```
After that we need to parse the replication strategy information and it can later be used to determine which nodes to use for load balancing.

I believe that that's the related code from gocql:
https://github.com/gocql/gocql/blob/964d7011f63d85c0c135ca47e2d06032c6be391b/topology.go#L71-L91
https://github.com/gocql/gocql/blob/5913df4d474e0b2492a129d17bbb3c04537a15cd/metadata.go#L544-L598

**Comment by cvybhu** [comment]
I'm not sure if I fully understand how the whole thing operates but I'm going to attempt something like this:

`Session` should hold `current_keyspace: Option<String>`
`current_keyspace` gets updated if a query response contains `table_spec` with keyspace name
(also in the future with USE statement?)

After updating `current_keyspace` we need to fetch keyspace details. (Tell `TopologyReader` to read this from the control connection or just do this in current query)

When we have `current_keyspace`'s details we send requests according to it's replication policy etc. (To be implemented in the future)

**Comment by psarna** [comment]
You actually have to keep information about all keyspaces (and the assumption is that clusters usually have a small number of them, e.g. 1, 5 or 1000, but not a million). The reason for that is that queries with explicitly stated keyspaces are legal, e.g. you can prepare a statement like that:
```cql
INSERT INTO some_keyspace.some_table (a, b, c) VALUES (?, ?, ?);
```
... regardless whether you sent a `USE <keyspace>` before or not.

So you're right that we need to fetch replication strategy information from the cluster, but instead of current keyspace (which might even not exist) we need to preventively fetch all of them.

Later, when a statement is prepared, it will return metadata about its keyspace (in this `table_spec` thing you mentioned), and we will use that to extract replication strategy details from our local cache of all replication strategies, and then apply our knowledge during load balancing.

Note: disregard unprepared statement, they are not interesting from the performance point of view. We don't use token/shard awareness for unprepared statements, so it's also pointless to try extracting keyspace information from them. We only care about prepared statements.

**Comment by cvybhu** [comment]
Thanks that clears up a lot
Then I will add something like `Arc<RwLock<HashMap<String, KeyspaceData>>>` in `Topology` and make `TopologyReader` update this during its `refresh`. Since there won't be that many keyspaces it could probably just select all keyspaces from the system table and put them in the hashmap.
Then prepared queries are going to find routing data for their keyspace in this map.
Unprepared queries go to `any_connection()`
