### ISSUE TITLE
Serialization error when incrementing a counter

### ISSUE THREAD

**Issue by prk3** [scylladb/scylla-rust-driver#1099]
I'm trying to increment a counter column with a query like this:

```cql
UPDATE monthly_counters SET action_counter = action_counter + ? WHERE ...;
```

My code is proving a value of type i64:

```rust
session.execute_unpaged(&increment_by_statement, (100i64,)).await?;
```

Execution fails at serialization of parameters:
```
Serializing values failed: SerializationError: Failed to serialize query arguments (i64,): failed to serialize column sent_activations: SerializationError: Failed to type check Rust type i64 against CQL type Counter: expected one of the CQL types: [BigInt]
```

It seems that i64 can't be used to increment a counter. I tried providing `CqlValue::BigInt(100)` and `num_bingint::BigInt`, none of those worked. How would I provide a value to that query?

**Comment by Lorak-mmk** [comment]
We have a section of documentation about `Counter` type: https://rust-driver.docs.scylladb.com/stable/data-types/counter.html

It sadly doesn't have an update example, but it does show what type to use: `use scylla::frame::value::Counter;`

So you example would be:
```
use scylla::frame::value::Counter;
session.execute_unpaged(&increment_by_statement, (Counter(100i64),)).await?;
```

**Comment by Lorak-mmk** [comment]
@wprzytula possible minor issue: I see there is `i64` deserialization for Counter: `impl_fixed_numeric_type!(i64, [BigInt | Counter]);`. For the sake of type safety and consistency with serialization shouldn't only the `Counter` type be able to deserialize `Counter` column?

**Comment by prk3** [comment]
> We have a section of documentation about `Counter` type: https://rust-driver.docs.scylladb.com/stable/data-types/counter.html
> 
> It sadly doesn't have an update example, but it does show what type to use: `use scylla::frame::value::Counter;`
> 
> So you example would be:
> 
> use scylla::frame::value::Counter;
> session.execute_unpaged(&increment_by_statement, (Counter(100i64),)).await?;

I missed that doc. Your solution works like a charm. Thank you! Fell free to close this issue one you figure out what to do with serialization vs deserialization type discrepancy.

**Comment by Lorak-mmk** [comment]
For completeness, I opened a PR that adds an example snippet that updates the counter value: https://github.com/scylladb/scylla-rust-driver/pull/1100

**Comment by Lorak-mmk** [comment]
> > [@wprzytula](https://github.com/wprzytula) possible minor issue: I see there is `i64` deserialization for Counter: `impl_fixed_numeric_type!(i64, [BigInt | Counter]);`. For the sake of type safety and consistency with serialization shouldn't only the `Counter` type be able to deserialize `Counter` column?
> 
> Agreed. I encourage you to fix that.

https://github.com/scylladb/scylla-rust-driver/pull/1106
