### ISSUE TITLE
Update user-facing `getReplicas` API

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla-rust-driver#1129]
## Metadata User-facing `getReplicas` API changes
If driver have user-facing API to get replica list we need to adapt it to tablets:
1. To accomodate tablet requirements new optional parameter `table` should be added, alternatively another method could be implemented with additional `table` parameter.
2. If target `table` is not `tablet-based` it should return `old` vnode-based result
3. If target `table` is `tablet-based` it should return known tablet replicas for given token
4. if there is no tablet record for given token, it should return empty list

**Comment by Lorak-mmk** [comment]
Already working this way!
