### ISSUE TITLE
TableSpecDiffersAcrossColumns when preparing a batch

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/scylla-rust-driver#1134]
Batch statement can contain multiple statements, and they can possible target different tables. Those statements can contain bind markers. An example of such statement:
```
BEGIN BATCH
    INSERT INTO friends (account_id, friend_id) VALUES (?, ?);
    DELETE FROM enemies WHERE account_id = ? AND enemy_id = ?;
APPLY BATCH;
```

If such statement is prepared, the bind markers will have different table specs, which 0.15 driver doesn't consider a possibility, so it throws an error:

```
called `Result::unwrap()` on an `Err` value: CqlResultParseError(PreparedParseError(PreparedMetadataParseError(ColumnSpecParseError(ColumnSpecParseError { column_index: 2, kind: TableSpecDiffersAcrossColumns(TableSpec { ks_name: "ks", table_name: "friends" }, TableSpec { ks_name: "ks", table_name: "enemies" }) }))))
```

Credits to Johhny Bike from User Slack for reporting this!

**Comment by wprzytula** [comment]
This is a serious regression. I suggest releasing 0.15.1 containing the fix. WDYT @Lorak-mmk @dkropachev?

**Comment by Lorak-mmk** [comment]
I agree
