### ISSUE TITLE
Deprecate legacy APIs before we delete them in 1.0

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#1139]
There are a number of API items that we consider legacy, but still haven't labeled with `#[deprecated]` attributes. Let's do that in 0.16, so that in 1.0 we can remove them.

This is going to be a list of such items:
- `LegacySerializedValues`,
- TODO

**Comment by Lorak-mmk** [comment]
Actually let's do that in 0.15.1. It's possible we won't release 0.16 because of time constraints, especially if we want to release release candidate for 1.0
