### ISSUE TITLE
Allow passing multiple node addresses to session::connect

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#119]
We currently only allow passing a single address to `Session::connect`. It's fine for token-aware routing, since we then pull the topology info and establish connections to each node anyway, but we should also allow non-token-aware users to have sensible load balancing (e.g. round robin over multiple addresses). Token awareness is kind of hardcoded for now, but it's not going to always be the case, so users should have other options.

In order to do that, we should allow passing multiple addresses to connect, just like other drivers tend to do, e.g. `Session::connect(&[addr1, addr2, addr3])`. These addresses should then be inserted into a pool, which can be used for load balancing.

**Comment by piodul** [comment]
I agree that we should make it possible to pass multiple addresses to `Session::connect`, but I don't think I agree with the motivation (if I understood it correctly, correct me if I'm wrong).

I assume that the problem with our current implementation of non-token-aware routing (which is already used, for example, for non-prepared statements) is that we randomly choose a connection from the pool of open connections that we have at the moment, and we start with connection to a single node.

Passing multiple nodes to `Session::connect` will help, but is not a proper solution to that - in case we add new nodes to the cluster and won't use token-aware queries, the driver won't establish connections to the new nodes. Aside from that, the user has to know IPs of all nodes to utilize the cluster fully.

Instead, what I think we could do when doing non-token-aware operations is to randomly choose a node _from the current list of nodes_, and then use a connection to it, lazily opening it if needed.

Another idea is to ditch lazy initialization and have a worker fibre which listens for changes in the topology ring and opens/closes connections when the topology of the cluster changes. I think I like this idea more, but it's probably more work.

Coming back to the idea of passing multiple IPs, it's a good idea for other reasons - for example, some contact nodes from the list might not be available at the moment, so this provides redundancy.

**Comment by psarna** [comment]
Right, we should fetch topology regardless. Still, if fetching topology failed for some reason, the initial list can be used as contact points for load balancing, for lack of better alternative.
