### ISSUE TITLE
Add Scylla Sphinx Theme to Rust Driver Docs 

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla-rust-driver#120]
Just like the Python and Java Driver, the Scylla Sphinx Theme should be applied to the Rust Driver.

The Process includes:

- Following the steps - https://github.com/scylladb/sphinx-scylladb-theme/blob/master/README.rst
- Testing the output
- Making sure everything we display is branded Scylla not Datastax
- Making sure the links are all directed to Scylla
- Adding multi-version when the next version goes out.

**Comment by piodul** [comment]
Fixed in https://github.com/scylladb/scylla-rust-driver/pull/215
