### ISSUE TITLE
Warn about connecting to the non-shard-aware port

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#153]
Current main: 187fda1d8c193d4a3e944dd73e119270aa6e8fd2

Recent versions of Scylla expose two ports for drivers:

- Old, "non-shard-aware" - by default 9042,
- New, "shard-aware" - by default 19042.

The only difference between them is that, in the case of the new one, a driver can choose which shard will handle the connection by choosing a source port. In the case of the old port, Scylla chooses the shard and the driver has no control over it.

Currently, the driver tries to establish a connection per shard only if the new port was specified while creating the session. While it's possible to do the same with the old port, this is harder to do and cannot be made as robust as with the new port, so we didn't implement it (yet?).

Because of that, a user will only have one connection per node if they specify the old port when connecting. This will lead to worse performance. We should warn the user about this if Scylla supports the new port, but the user connects to the old port.

**Comment by psarna** [comment]
@asledz

**Comment by piodul** [comment]
Closing because it is no longer relevant.

With recent versions of the driver (0.3.0+), now it's better to provide the non-shard-aware port. The driver learns about the shard-aware port on the first connection and chooses between those two ports, whichever works better in current situation.
