### ISSUE TITLE
Integrate with a logging library

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#158]
We should use one of the popular crates for logging in order to provide better diagnostics of the driver.
One possible candidate: https://crates.io/crates/log

**Comment by dtzxporter** [comment]
I would appreciate the ability to be able to plug the logger as the user. Maybe exposing an interface (that log is used as the default) with the ability to provide custom callbacks for logging?

**Comment by psarna** [comment]
Makes sense, an interface would be simple enough and the log crate can be used for the standard implementation of it.

**Comment by ansrivas** [comment]
@psarna lately the libraries have been migrating to [tracing](https://github.com/tokio-rs/tracing) and it also has the support for `tracing-log`, with respect to logging, this could be interesting for end-users as well.
