### ISSUE TITLE
Integration test support in CI

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla-rust-driver#16]
Let's make a Scylla instance available in the CI environment for integration tests, similar to what the Mongo driver does:

https://github.com/mongodb/mongo-rust-driver#running-the-tests

We can use the Scylla Docker image for this: https://hub.docker.com/u/scylladb

**Comment by Jasperav** [comment]
@penberg Can this be closed? The CI spins up a Scylla instance and runs the DB tests

**Comment by psarna** [comment]
Certainly, let's close
