### ISSUE TITLE
Linking to unmaintained crate

### ISSUE THREAD

**Issue by krojew** [scylladb/scylla-rust-driver#165]
The README links to the cdrs crate, which is unmaintained. Please consider adding a remark or linking to the maintained async version: https://crates.io/crates/cdrs-tokio

**Comment by psarna** [comment]
Sure, makes sense. If you have good suggestion as to the remark contents, feel free to send a pull request. Otherwise we'll just update the link in the footer.

**Comment by krojew** [comment]
I would suggest simply updating the link, since users should not be using unmaintained crates anyway.
