### ISSUE TITLE
Disallow query that sets the keyspace by using the query method

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#176]
This is currently in the codebase:

```
async fn query_no_metrics(
    &self,
    query: impl Into<Query>,
    values: impl ValueList,
) -> Result<Option<Vec<result::Row>>, QueryError> {
    let query: Query = query.into();
    let query_text: &str = query.get_contents();

    // In case the user tried doing session.query("use keyspace ks") run session::use_keyspace
    if query_text.to_lowercase().starts_with("use ") {
        eprintln!("Warning: Raw USE KEYSPACE queries are experimental, please use session::use_keyspace instead");

        let mut keyspace_name: &str = &query_text["use ".len()..].trim_end_matches(';').trim();

        let case_sensitive: bool = keyspace_name.starts_with('"');

        keyspace_name = keyspace_name.trim_matches('"');

        return self
            .use_keyspace(keyspace_name, case_sensitive)
            .await
            .map(|_| None);
    }
    ...
```

I propose to remove the logic because:
1. It allocates a string for literally every query, for something that will happen only once or just a few times in a normal application (I guess?)
2. There is already a warning, telling us that we misuse the query method by setting a keyspace.

Sine this repo is fairly new and not even on crates.io, I propose we can change the logic like so:
```
    if query_text.starts_with("use ") || query_text.starts_with("USE ") {
        panic!("Don't set the keyspace by this method, but use session::use_keyspace");
    }
```

I think it would be better to just crash everything instead of handling wrong user input (and the fix for users is really simple).

**Comment by cvybhu** [comment]
There was some discussion about this choice in the original PR: #160

There is a use case of someone that loads many queries from a file and passes them to `session.query()`
We wanted to make this as painless as possible without the user having to parse `USE` queries themselves .
After implementing #168 doing use keyspace like this could probably be supported without the warning.

About the allocation maybe we could change it to a regex to keep case insesitivity, but for now performance is not the top priority - we will profile the code after getting all basic features done.

**Comment by psarna** [comment]
But wait, this code wouldn't allocate for every query, but only for queries that start with `use`, right? These kind of queries are not expected to be common (as opposed to, for instance, executing prepared statements), so an allocation here will not influence the overall performance.

Performance actually is one of the top priorities, but on the fast path - we want the most common operations to be fast, while for the less common ones (like `use keyspace`) we'd prefer user experience over raw performance - and #168 would make everything happen automagically from the user's perspective.

**Comment by piodul** [comment]
Ah, the current logic __does__ allocate, but the snippet here does not reflect the actual code!

The condition is as follows:

```rust
if query_text.to_lowercase().starts_with("use ") {
    // ...
}
```

`to_lowercase()` creates a new string, so there is an allocation. We can use a regex as @cvybhu said, or use [`str::eq_ignore_ascii_lowercase`](https://doc.rust-lang.org/std/primitive.str.html#method.eq_ignore_ascii_case).

**Comment by psarna** [comment]
Alright, that's a performance bug :) `str::eq_ignore_ascii_lowercase` sounds like a perfect solution.

**Comment by Jasperav** [comment]
@piodul Woops, that right. I edited the original code, so in the code snippet in my question it doesn't reflect the real code indeed. I will edit that accordingly.

I think `str::eq_ignore_ascii_lowercase` will indeed be sufficient, nice find! Comparing can than be done by something like this:

```
...
let query_text: &str = query.get_contents();
if query_text.len() > 4 && query_text[0..=3].eq_ignore_ascii_lowercase("use ") { 
...
}
```

I guess that can already place the current code, can someone verify? I can make a PR if needed.

**Comment by psarna** [comment]
> @piodul Woops, that right. I edited the original code, so in the code snippet in my question it doesn't reflect the real code indeed. I will edit that accordingly.
> 
> I think `str::eq_ignore_ascii_lowercase` will indeed be sufficient, nice find! Comparing can than be done by something like this:
> 
> ```
> ...
> let query_text: &str = query.get_contents();
> if query_text.len() > 4 && query_text[0..=3].eq_ignore_ascii_lowercase("use ") { 
> ...
> }
> ```
> 
> I guess that can already place the current code, can someone verify? I can make a PR if needed.

Sounds good, although you might want to call `as_bytes()` on the input string and use the version that operates on raw bytes (thanks @piodul for pointing it out) https://doc.rust-lang.org/std/primitive.slice.html#method.eq_ignore_ascii_case , to avoid utf-8 issues, because we ultimately just want to compare first 4 bytes. Also, ` query_text.len() > 4` will work because keyspace names cannot be empty, but ` query_text.len() >= 4` will also suffice in this case :)

**Comment by Jasperav** [comment]
Since the PR is merged which improves the efficiency of checking if a keyspace is used, this issue can be closed
