### ISSUE TITLE
Implement time-related types with standard Rust representation

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#182]
#175 introduced serialization mechanisms for CQL types used to express time (timestamp, datetime, date), but they are represented in a raw form - an integer - which is not ideal for user experience. Instead, these types can be expressed with standard Rust mechanisms from https://doc.rust-lang.org/std/time/index.html .

Refs #104 #97

**Comment by mkawalec** [comment]
There is one bug I've found which might be automagically fixed when moving to a new timestamp representation. The following query:
```
session.execute("SELECT * FROM table WHERE timestamp_field = ?", &(&0,)).await?
```
fails with the the error:
```
ScyllaDB query error: Database returned an error: The query is syntatically correct but invalid, Error message: Exception while binding column starts_at: marshaling error: Validation failed for timestamp - got 1 bytes
```

**Comment by avelanarius** [comment]
Old issue, it's already implemented.
