### ISSUE TITLE
Precompute replica sets

### ISSUE THREAD

**Issue by havaker** [scylladb/scylla-rust-driver#190]
When PR #172 is merged, replica sets will be calculated each time some query is executed. To improve driver's performance, we could precompute replicas for each (keyspace x vnode) pair (as does gocql driver).

**Comment by mykaul** [comment]
[#pr172](https://github.com/scylladb/scylla-rust-driver/pull/172) is now merged! What's the next step?

**Comment by piodul** [comment]
@mykaul This should be fixed as a part of the load balancing module refactor (#408). There is a PR in progress (https://github.com/scylladb/scylla-rust-driver/pull/612).

**Comment by piodul** [comment]
The new implementation of load balancing was merged, and it precomputes replica sets. I'll close this.
