### ISSUE TITLE
Resume paging

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#219]
In cdrs(_tokio), the user can page with state: https://github.com/krojew/cdrs-tokio/blob/40110835db2f3695e8176a8250caa67ca22e22bc/examples/paged_query.rs#L210. This means the server can send clients the current paging state, which in turn can be used to retrieve the next page. 

I don't see any option how to set/get the current cursor for paging. I also can not see how to specify the number of rows to retrieve for each page. I would expect to see this functionality demonstrated in https://github.com/scylladb/scylla-rust-driver/blob/main/examples/select-paging.rs.

**Comment by psarna** [comment]
We went with an iterator approach which hides the underlying paging logic. The server still sends back the current paging state and it's kept as part of the iterator's state.

As for setting the number of rows in a page, it's already possible via `set_page_size`: https://cvybhu.github.io/scyllabook/queries/paged.html#configuring-page-size

... but I agree that it should be demonstrated in the paging example.

**Comment by Jasperav** [comment]
@psarna Is it still possible to expose the pager state? The python driver already implemented this feature: https://python-driver.docs.scylladb.com/3.22.0-scylla/query_paging.html#resume-paged-results

**Comment by piodul** [comment]
I think exposing the paging state shouldn't be too hard.

- We already have `Session::query` and `Session::execute` methods which fetch only a single page. They return the `QueryResult` type, so we could add a paging state field to it.
- We could make it possible to set paging state for `Query` and `PreparedStatement`.

**Comment by Jasperav** [comment]
@piodul  is there any chance it will be implemented in the short future? I want to migrate some projects to this crate, but I rely on the resume paging functionality

**Comment by Jasperav** [comment]
Thanks for the quick implementation!
