### ISSUE TITLE
Remove stray eval_rst paragraphs from mdbook generation

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#229]
Now that we support both mdbook docs and the sphinx theme from #215, let's add https://gist.github.com/cvybhu/3874df86a64d146645d13d48fe389e37 to the book generation job to remove redundant `eval_rst` paragraphs from the book, because they don't look very nice.

/cc @cvybhu

**Comment by piodul** [comment]
Fixed in https://github.com/scylladb/scylla-rust-driver/pull/239
