### ISSUE TITLE
Make the topology refresh duration configurable

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#232]
Topology information is currently refreshed at the hardcoded rate of 1/minute:
https://github.com/scylladb/scylla-rust-driver/blob/bbbfeb9bef7787d7a884eb29c5cc62be1ca9b6bf/scylla/src/transport/cluster.rs#L296

Let's make this value configurable instead - in particular, it can be useful for users which:
- do not want any unexpected traffic, in which case the refreshing can be disabled
- expect the topology to change often and don't want to rely on events, in which case they set it up to, say, 1 per second

/cc @cvybhu

**Comment by rishabharyal** [comment]
@psarna, I assume we also need to be able to set the frequency from SessionBuilder?

**Comment by psarna** [comment]
Most likely! I'm no longer maintaining this project though, so let's wait for some other maintainer to confirm and review your contribution 🫡

**Comment by piodul** [comment]
@rishabharyal Yes, if you add an option to `SessionConfig` then please also add a corresponding method in the `GenericSessionBuilder`.

**Comment by rishabharyal** [comment]
Thanks for the prompt @piodul. I have raised a PR with the changes.
