### ISSUE TITLE
ProtocolError on overloaded Scylla node

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#241]
During testing I encountered a strange error

I started a 6 node cluster and tried doing many queries, but it looked like Scylla ran out of memory.
Then the driver started reporting `ProtocolError` stating that it failed to parse a frame sent from Scylla
This is bad, we don't want to report fatal errors when Scylla gets overloaded.

More or less what I did:
* Started a cluster similar to the one in https://github.com/cvybhu/rust-driver-tests but with nodes limited to 750M memory
* Ran a test similar to https://github.com/cvybhu/rust-driver-tests/tree/main/programs/dc_network_strategy/ but with more queries

This issue is here to remind about this problem
When I get a free moment I will try to reproduce it on a minimal example and see whats going on.

**Comment by wprzytula** [comment]
Irreproducible, stalled - closing.
