### ISSUE TITLE
Switch to a different crate for lz4 compression/decompression

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#268]
Currently, the driver uses the [`compress`](https://github.com/rusty-shell/rust-compress) crate for lz4 compression/decompression. While it seems to correctly compress and decompress lz4 data, the crate states in its readme that it is a work in progress and not of production quality. There doesn't seem to be much work being done on it - it's over 7 years old and the last change was committed a year ago.

There are other crates for lz4 compression in Rust's ecosystem, so perhaps we should switch. One option is [`lz4_flex`](https://lib.rs/crates/lz4_flex):
- It has configurable safety levels (through cargo features): no unsafe code, unsafe code with bound checks, and unsafe code without any bound checks. The first option is the default, but also the slowest - by sacrificing safety, more speed can be squeezed out.
- It claims that its safe rust implementation has better performance than another safe rust crate (`lz4-fear`), and its unsafe rust implementation is not too far off from `lzzzz`, which uses bindings to the liblz4 crate.
- It has a nice API which allows to compress data into a slice, instead of returning a `Vec` with compressed data. The crate we are using now does not have this feature. Because we need to put the whole frame into one buffer so that we have exactly one write invocation for each frame, this means that we currently have to copy the compressed body into another vector along with the header. If we had a posssibility to put data into an existing slice, we can save one allocation on the send path.

**Comment by psarna** [comment]
It's something we'd be interested in seeing done!

**Comment by piodul** [comment]
We switched to the lz4_flex crate in https://github.com/scylladb/scylla-rust-driver/pull/380. However, we could still improve efficiency of the serialization by avoiding an allocation in `compress_append`. I created https://github.com/scylladb/scylla-rust-driver/issues/383 to track that, meanwhile I'm closing this issue.
