### ISSUE TITLE
[Feature] Get row by name

### ISSUE THREAD

**Issue by SeanOMik** [scylladb/scylla-rust-driver#271]
Currently, the only way to get a row is by using indexes. Although it works fine, it can be difficult when modifying the structure of tables, and makes it harder to read the code. I'm coming from CDRS and they have a [`by_name`](https://github.com/AlexPikalov/cdrs/blob/7de346341a9fd72135127ebabd5240d4c3a7de7a/src/types/mod.rs#L79) trait which is implemented by their `Row` type.

I'm not sure if this is even possible on this driver since I haven't looked at the source. It also isn't a high priority feature, it's more of a QOL feature.

**Comment by wprzytula** [comment]
This is going to be solved by #462.

**Comment by wprzytula** [comment]
Done in #1057.
