### ISSUE TITLE
Consider adding a default serial consistency level

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#277]
Using lightweight transactions in CQL requires setting an additional consistency level, the so called serial consistency level, on top of the regular one. The serial consistency level can only take two values: SERIAL and LOCAL_SERIAL. There's currently no default, so using lwt results in an error message: `Consistency level for LWT is missing for a request with conditions`. We should consider picking a sensible default value in order to improve the user experience of the driver.

**Comment by humb1t** [comment]
Would be great.
