### ISSUE TITLE
Empty values are not handled

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#278]
It turns out that apart from `some value` and `null`, a value in a table can also be `empty`. We handle `value` and `null` properly, but `empty` is not handled at all. When an empty value is returned in a query the driver fails with an error.

To reproduce:
1. Start Scylla
2. Use `cqlsh` to create test data:
```cql
create keyspace ks with replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
create table ks.t (p int primary key, r int);
insert into ks.t (p, r) values (0, blobasint(0x));
```
3. Now use the driver to select from `ks.t`
```bash
$ cargo run --example cqlsh-rs
Connecting to 127.0.0.1:9042 ...
>> select * from ks.t;
Error: Invalid message: Error parsing message: Could not serialize frame: Buffer length should be 4 not 0
```

**Comment by piodul** [comment]
@cvybhu Is there anything else left to do here? I can see that we have the `CqlValue::Empty` variant, introduced in #317.

**Comment by cvybhu** [comment]
> @cvybhu Is there anything else left to do here? I can see that we have the CqlValue::Empty variant, introduced in #317.

:+1: It's solved, we can close this.
