### ISSUE TITLE
Actix-web concurrency test is very slow

### ISSUE THREAD

**Issue by dragon-D** [scylladb/scylla-rust-driver#282]
I use actix-web development. Test concurrency with ab is very slow
```
use scylla::transport::session::Session;
use actix_web::{get, middleware, web, App, HttpRequest, HttpResponse, HttpServer};
use chrono::prelude::*;
use scylla::transport::session::Session;
use scylla::SessionBuilder;
    
extern crate chrono;


async fn index_async(req: HttpRequest) -> &'static str {
    println!("REQ: {:?}", req);
    "Hello world!\r\n"
}

#[get("/")]
async fn no_params() -> &'static str {
    "Hello world!\r\n"
}

#[get("/test")]
async fn test() -> &'static str {



    let session = SessionBuilder::new()
        .known_nodes(&["10.10.10.2:9042"])
        .user("test", "test")
        .build()
        .await
        .unwrap();
    let rows = session
        .query("SELECT a, b, c FROM ks.t;", &[])
        .await
        .unwrap()
        .rows
        .unwrap();

    let dt = Local::now();
    println!("{:?} \tRead {} rows", dt.timestamp_millis(), rows.len());

    "test!\r\n"
}


#[actix_web::main]
async fn main() -> std::io::Result<()> {

    HttpServer::new(|| {
        App::new()
            .wrap(middleware::DefaultHeaders::new().header("X-Version", "0.2"))
            .wrap(middleware::Compress::default())
            .wrap(middleware::Logger::default())
            .service(test)
    })
    .bind("127.0.0.1:8989")?
    .run()
    .await
}
```
This is the test result of ab ```ab -n 200 -c 200 -k http://10.10.10.3:8989/test ```
```
Concurrency Level:      200
Time taken for tests:   1.340 seconds
Complete requests:      200
Failed requests:        0
Write errors:           0
Keep-Alive requests:    200
Total transferred:      34200 bytes
HTML transferred:       2800 bytes
Requests per second:    149.23 [#/sec] (mean)
Time per request:       1340.185 [ms] (mean)
Time per request:       6.701 [ms] (mean, across all concurrent requests)
Transfer rate:          24.92 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    6   1.2      6       8
Processing:    38 1264  88.1   1269    1301
Waiting:       30 1264  88.7   1269    1301
Total:         38 1269  88.6   1275    1308

Percentage of the requests served within a certain time (ms)
  50%   1275
  66%   1279
  75%   1282
  80%   1286
  90%   1296
  95%   1299
  98%   1302
  99%   1303
 100%   1308 (longest request)
```
This is part of the request processing completion time. You can see that the waiting time between the first request and the second request is very long, just the time in the ab result.
```
1629207689926 	Read 100 rows
1629207691177 	Read 100 rows
1629207691177 	Read 100 rows
1629207691179 	Read 100 rows
1629207691179 	Read 100 rows
1629207691179 	Read 100 rows
1629207691179 	Read 100 rows
1629207691180 	Read 100 rows
1629207691180 	Read 100 rows
1629207691180 	Read 100 rows
1629207691181 	Read 100 rows
1629207691181 	Read 100 rows
1629207691181 	Read 100 rows
1629207691181 	Read 100 rows
1629207691182 	Read 100 rows
1629207691183 	Read 100 rows
1629207691183 	Read 100 rows
```
scylladb version "Scylla version 3.2.1-0.20200122.e3e301906d5"

cargo.toml
```
[dependencies]
chrono = "0.4.19"
scylla = "0.2.1"
actix-web = "4.0.0-beta.8"
futures = "0.3.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
bytes = "1.0.1"
actix-service = "2"
```

**Comment by cvybhu** [comment]
Building a `Session` is a slow and heavy operation.
Doing it in every request will cause poor performance.

To improve performance try to have only one  `Arc<Session>` shared between requests.

**Comment by dragon-D** [comment]
After I tried to use Arc
```
use actix_web::{get, middleware, web, App, HttpRequest, HttpResponse, HttpServer};
use chrono::prelude::*;
use std::sync::Arc;
use scylla::transport::session::Session;
use scylla::SessionBuilder;
use futures::future::join_all;
use rand::Rng;

extern crate chrono;

#[derive(Clone)]
pub struct AppData{
    db:Arc<Vec<Session>>
}

#[get("/test")]
async fn test(data: web::Data<AppData>) -> &'static str {

    let r = rand::thread_rng().gen_range(0..100);
    let s = data.db.clone();

    let rows = s[r]
        .query("SELECT a, b, c FROM ks.t;", &[])
        .await
        .unwrap()
        .rows
        .unwrap();

    let dt = Local::now();
    println!("{:?} \tRead {} rows", dt.timestamp_millis(), rows.len());

    "test!\r\n"
}


#[actix_web::main]
async fn main() -> std::io::Result<()> {
    println!("开始运行");
    let session_builder = SessionBuilder::new()
         .known_nodes(&["10.2.2.3:9042"])
        .user("test", "test");
    let sessions: Vec<Session> = join_all(
        (0..100)
            .map(|_: usize| async { session_builder.build().await.unwrap() })
            .collect::<Vec<_>>(),
    )
    .await;

    let session = Arc::new(sessions);
    // println!("session {:?}", session);
    HttpServer::new(move|| {
        let app_state = AppData {
            db:session.clone()
        };
        let data = web::Data::new(app_state);
        App::new()
        .app_data(data)
        .service(test)

    })
     .bind("10.2.2.2:8989")?
    .run()
    .await
}
```
Then re-tested with ab

```
Concurrency Level:      1000
Time taken for tests:   103.634 seconds
Complete requests:      300000
Failed requests:        0
Write errors:           0
Keep-Alive requests:    300000
Total transferred:      44100000 bytes
HTML transferred:       2100000 bytes
Requests per second:    2894.81 [#/sec] (mean)
Time per request:       345.446 [ms] (mean)
Time per request:       0.345 [ms] (mean, across all concurrent requests)
Transfer rate:          415.56 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.2      0      [27](url)
Processing:    32  345 184.1    263    1336
Waiting:        6  345 184.1    263    1336
Total:         32  345 184.1    263    1336
[](url)
Percentage of the requests served within a certain time (ms)
  50%    263
  66%    301
  75%    352
  80%    449
  90%    690
  95%    778
  98%    830
  99%    854
 100%   1336 (longest request)
```
The maximum time is still relatively slow

cpu: 8
memeny: 16G

[result of flamegraph](https://pic.stackoverflow.wiki/uploadImages/113/218/176/164/2021/08/18/19/08/18e2bce6-761d-4173-9025-615341f61a45.svg)

**Comment by piodul** [comment]
You are not using prepared statements. This driver does not prepare them automatically when using `Session::query`, you have to do it yourself. Prepared statements are faster when used multiple times because Scylla does not have to parse them every time the statement is executed. Like `Session`, you should create the prepared statement once at startup and then reuse it through e.g. `Arc`. See [`Session::prepare`](https://docs.rs/scylla/0.2.1/scylla/transport/session/struct.Session.html#method.prepare) and [`Session::execute`](https://docs.rs/scylla/0.2.1/scylla/transport/session/struct.Session.html#method.execute) for more details.

Additional tips which may help:

1. You don't need 100 sessions, one should be sufficient. You can run many concurrent requests with a single session.
1. You are running a full scan on every request. A full scan is a select query without any WHERE restriction. Full scans are not an efficient operation and you should not run them that often. A more realistic option for this benchmark would be to e.g. select rows from a single partition: `SELECT a, b, c FROM ks.t WHERE a = ?`.

**Comment by dragon-D** [comment]
> You are not using prepared statements. This driver does not prepare them automatically when using `Session::query`, you have to do it yourself. Prepared statements are faster when used multiple times because Scylla does not have to parse them every time the statement is executed. Like `Session`, you should create the prepared statement once at startup and then reuse it through e.g. `Arc`. See [`Session::prepare`](https://docs.rs/scylla/0.2.1/scylla/transport/session/struct.Session.html#method.prepare) and [`Session::execute`](https://docs.rs/scylla/0.2.1/scylla/transport/session/struct.Session.html#method.execute) for more details.
> 
> Additional tips which may help:
> 
> 1. You don't need 100 sessions, one should be sufficient. You can run many concurrent requests with a single session.
> 2. You are running a full scan on every request. A full scan is a select query without any WHERE restriction. Full scans are not an efficient operation and you should not run them that often. A more realistic option for this benchmark would be to e.g. select rows from a single partition: `SELECT a, b, c FROM ks.t WHERE a = ?`.

I think this is not caused by not using ```Session::prepare``` and ```Session::execute```. It can be seen that 50% of the result of ab is 263, and the maximum is 1336ms. You can also see it in the flame map I printed.

The data in the table ks.t is 100 rows, so I think this basic test and SELECT a, b, c FROM ks.t WHERE a =? Have little effect on scylladb

**Comment by kbr-** [comment]
> You don't need 100 sessions, one should be sufficient. You can run many concurrent requests with a single session.

The documentation should really emphasize that **you should use one session per entire application**, unless you have a very good reason not to (which you probably don't).
