### ISSUE TITLE
Add more information to `FromCqlValError`

### ISSUE THREAD

**Issue by humb1t** [scylladb/scylla-rust-driver#287]
Currently most of the error messages are hard to deal with.
[FromCqlValError](https://docs.rs/scylla/0.2.1/scylla/frame/response/cql_to_rust/enum.FromCqlValError.html) contains no information that makes root cause discovery process easier.
It would be great to have additional information in errors, for example in case of `ValIsNull` it may be helpful to know what column\field contains this null.

**Comment by injecto** [comment]
Absolutely agree, it's very hard to say which problem was exact without access to the data and the query log.

**Comment by jazvit** [comment]
Oh yeah! Many hours of my life were spent on blind error handling.

**Comment by piodul** [comment]
`FromCqlValError` is used in the `FromCqlVal` interface which does not have a concept of the number/name of column. I think a better place for this information would be `FromRowError`:

https://github.com/scylladb/scylla-rust-driver/blob/9a33c4b8413ee335ce8e6e8aeacc3c8de6bb87f8/scylla/src/frame/response/cql_to_rust.rs#L12-L18

@havaker ^
