### ISSUE TITLE
panic on creating session 

### ISSUE THREAD

**Issue by jazvit** [scylladb/scylla-rust-driver#299]
panic: Bug in Cluster::refresh_topology receiving: RecvError(())
file=scylla-0.2.1/src/transport/cluster.rs       line=145

**Comment by psarna** [comment]
Hi, just noticed this issue. Could you provide more context? Are you running the driver against Scylla or Cassandra? Are all nodes of the cluster healthy and reachable?

**Comment by psarna** [comment]
closing until more context arrives; I'll reopen the issue once we have more information
