### ISSUE TITLE
Multi node tests in CI

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#307]
We should add some tests that use a cluster of multiple nodes.
For example:
* Make a cluster of 3 scylla nodes
* Make one node unreachable from the driver (drop all packets from driver to this node)
* run `cargo test`

This would prevent bugs like: #306

It looks like `java-driver` uses `ccm` to run tests in their CI, we could do something similar.
https://github.com/scylladb/java-driver/blob/scylla-3.x/.github/workflows/tests.yml#L26

**Comment by Jasperav** [comment]
is `ccm` required? I guess a simple docker compose file, mention in #306, would also work. When a node is added to the cluster while this driver is running in an application, does this driver adds the new node in memory? Maybe that can be tested as well while fixing this issue

**Comment by piodul** [comment]
In https://github.com/scylladb/scylla-rust-driver/pull/489, we modified the CI to run tests on a 3-node cluster. We can additionally consider tests which will modify the cluster while they are running to tests how the driver behaves when the topology changes.

**Comment by Lorak-mmk** [comment]
Closing in favor of https://github.com/scylladb/scylla-rust-driver/issues/1097
