### ISSUE TITLE
Docs: enforce https

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla-rust-driver#322]
the doc site http://rust-driver.docs.scylladb.com does not enforce https
All it take is one checkbox https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

**Comment by mykaul** [comment]
@annastuchlik ? @avelanarius ? Anything I can help to close this small gap?

**Comment by tzach** [comment]
This is a checkbox the project maintainer need to set. A 1 minute work.

**Comment by mykaul** [comment]
> This is a checkbox the project maintainer need to set. A 1 minute work.

Checked. Now need to move references from http://... to https://... and ensure the old site is not published anymore.
