### ISSUE TITLE
0.3.0 release

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#332]
When can we expect the 0.3.0 (or 0.2.2) release to crates?

**Comment by psarna** [comment]
I want to push 0.3.0 this week. It would be nice to also include #329 in it, but that depends how the review goes - if any substantial changes would be necessary, I'll schedule #329 for another release and push 0.3.0 anyway

**Comment by psarna** [comment]
Done - #329 is scheduled for the next release.
