### ISSUE TITLE
Expose column spec information for the `_iter` interface

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#336]
Related to #271.

In #276, information about column names became available for the results of `Session::query` and `Session::execute` through the `QueryResult::col_specs` field.

We should also expose this information through the iterator object returned by `Session::query_iter` and `Session::execute_iter` methods.

**Comment by cvybhu** [comment]
I implemented it when adding `query_all` to `Session`, but eventually these changes were dropped.
There is a commit on this branch: https://github.com/cvybhu/scylla-rust-driver/commits/queryall-backup:

https://github.com/cvybhu/scylla-rust-driver/commit/6bf71829821a1969a8c19f05b43eadba17242040

**Comment by piodul** [comment]
Fixed by b46f913
