### ISSUE TITLE
Driver does not automatically re-prepare expired queries 

### ISSUE THREAD

**Issue by nemosupremo** [scylladb/scylla-rust-driver#342]
Driver Version: 0.2.1

I haven't yet confirmed if this a problem with the driver (or if it's fixed on 0.3.0), (kind of assuming given that this driver is so early).

If a prepared query expires in the database, then I believe what other drivers do is re-prepare the query. Currently the scylla-rust-driver just raises the error back tot he application.

```
Database returned an error: Tried to execute a prepared statement that is not prepared. Driver shoud prepare it again, Error message: No prepared statement with ID 85b1bde849f7781d9f5487ad113cee7d found.!
```

**Comment by psarna** [comment]
We also implemented automatic re-preparation since 0.1.0 if I remember correctly, so maybe it's a bug. Could you share the code snippet which triggered the error? Was it after the database was restarted? Also, are you using Scylla or Cassandra as the database? We'll try to reproduce the issue

**Comment by nemosupremo** [comment]
I think the issue might be when trying to use prepared statements inside of a batch:

```rust
let save: PreparedStatement = match cass
    .prepare(
        "INSERT INTO minute
    (key, value) VALUES
    (?, ?)",
    )
    .await
{
    Ok(p) => p,
    Err(err) => {
        log::error!("Failed to prepare save: {}", err);
        panic!()
    }
};

let values_dev = vec![("foo", "bar"), ("bar", "baz")]
    .iter()
    .map(|(id, x)| (id, x))
    .collect::<Vec<_>>();
let mut batch: scylla::batch::Batch = Default::default();
for _ in values_dev.iter() {
    batch.append_statement(save.clone());
}
if let Err(err) = cass.batch(&batch, &values_dev).await {
    panic!("Failed to write data to cassandra: {}!", err);
};
```

**Comment by nemosupremo** [comment]
Looks like it might be related to: https://github.com/scylladb/scylla-rust-driver/pull/103#pullrequestreview-526452484

Was this ever resolved?

**Comment by nemosupremo** [comment]
Ok, had some time to look at the code:

`execute` has some code to reprepare: 

https://github.com/scylladb/scylla-rust-driver/blob/8400f85de0b2e73b275e64a5ce7b498cdf26be90/scylla/src/transport/connection.rs#L452

but `batch` doesn't:

https://github.com/scylladb/scylla-rust-driver/blob/8400f85de0b2e73b275e64a5ce7b498cdf26be90/scylla/src/transport/connection.rs#L546
