### ISSUE TITLE
Add support for different partitioners

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#352]
Our driver currently assumes murmur3 tokens, which is more or less true for Scylla (except https://github.com/scylladb/scylla-rust-driver/issues/194), but Cassandra and other compatible solutions like Amazon Keyspaces offer many different partitioning schemes. We should consider the following:
* implementing a few partitioning schemes that Cassandra supports - e.g. RandomPartitioner based on md5 or ByteOrderedPartitioner which simply interprets bytes from the key as the token
* making sure that unsupported partitioners also work fine, except that they will not support token awareness correctly; for instance, Amazon Keyspaces uses `com.amazonaws.cassandra.DefaultPartitioner`; that bullet point is solved by #351

**Comment by avelanarius** [comment]
I think this issue can be closed now (since we have CDCPartitioner and the second "making sure that unsupported partitioners also work fine" looks fixed in the merged PR)? (cc @piodul)
