### ISSUE TITLE
Expose prepared statement metadata (column types)

### ISSUE THREAD

**Issue by pkolaczk** [scylladb/scylla-rust-driver#359]
Some generic apps don't control the schema, but still have to issue queries.
For example if my app receives an integer parameter 123  from a user, and although it knows it is an integer, but doesn't know the *size* of that integer on the C*/Scylla side, then it can't properly send it to the database without risking type mismatch.

**Comment by piodul** [comment]
Fixed in https://github.com/scylladb/scylla-rust-driver/pull/451
