### ISSUE TITLE
Allow binding query parameters by name (or document if already supported)

### ISSUE THREAD

**Issue by pkolaczk** [scylladb/scylla-rust-driver#360]
CQL allows named placeholders like `"SELECT * FROM table WHERE name = :name"`.
How to bind them by name?

**Comment by psarna** [comment]
Named markers are not supported yet. Ref: https://github.com/scylladb/scylla-rust-driver/blob/1bc1ec82b8fc60ef29137d76e894759f542e33ae/scylla/src/frame/request/query.rs#L18)

Thanks for reporting!
