### ISSUE TITLE
Implemented TCP keepalive configuration option

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#394]
Implementing tcp keepalive flag for sessions and connections should be added, in case users want to ensure that their connections don't time out without traffic.

**Comment by piodul** [comment]
Duplicate of https://github.com/scylladb/scylla-rust-driver/issues/132 ?

`tokio::net::TcpStream` used to have a [`set_keepalive`](https://docs.rs/tokio/0.1.12/tokio/net/struct.TcpStream.html#method.set_keepalive) method, but no longer has one. We probably could implement "manual" keepalives, e.g. sending some cheap query every keepalive period. I think that the Java and the Python driver use this method.

**Comment by psarna** [comment]
Ah yes, closing this one as duplicate
