### ISSUE TITLE
Show a warning when an incorrect datacenter name is provided

### ISSUE THREAD

**Issue by havaker** [scylladb/scylla-rust-driver#406]
If a user provides an incorrect datacenter name to the `DcAwareRoundRobinPolicy`, driver does not emit any feedback about it. This should not be the case, the user should find out about it.

**Comment by wprzytula** [comment]
Closing, as `DcAwareRoundRobinPolicy` exists no longer in the codebase after the load balancing refactor (#612).
Note that similar problem exists for current implementation of `DefaultPolicy` (#747), but the referenced issue already tracks the problem.
