### ISSUE TITLE
[question] does QueryResult.paging_state require the scylla server to keep any resources in RAM or on disk?

### ISSUE THREAD

**Issue by avkonst** [scylladb/scylla-rust-driver#431]
I expect the answer should be "NO", because the client should paginate based on latest row token and clustering key values... but I am not 100% sure and would like to receive a confirmation. Could you please explain if my understand is right or wrong and elaborate a bit more on details?

The reason I am asking is I would like to "save" paging_state and use it later to resume page fetching from the same or another process (ie. different connection session). I also would like to make sure that paging_state is "tolerant" to scylla server(s) restarts. Could you please confirm that what I am planning to do is correct to do.

Thanks!

**Comment by denesb** [comment]
The paging state also stores the set of replicas used for the last page. On the next page, the coordinator will try to use the same replicas to hit the reader caches on said replicas. The reader cache has a time-based eviction policy so readers there will not be "pinned" by you holding on to paging state.
So it is safe to hold on to a paging state cookie and resume the query much later. You just won't hit the reader caches on the first page after resuming.

**Comment by avkonst** [comment]
Many thanks!

**Comment by psarna** [comment]
@avkonst once you're satisfied with the answers and/or you verify that everything works correctly, feel free to close this issue :)

**Comment by psarna** [comment]
Also, you might want to join our Slack channel for quick questions: http://slack.scylladb.com/ , the channel name is **#rust-driver** and the community is very helpful and responsive
