### ISSUE TITLE
Parsing a UDT with a field not present in a struct results in a BadCqlType error

### ISSUE THREAD

**Issue by merlleu** [scylladb/scylla-rust-driver#432]
Hello,

I've been using this driver for a few months in production but I have a little problem: 
Some of our services need to read data from scylla but their cql schema is not up-to-date, so when a field is added to an UDT, any column containing this UDT would no longer be readable using this driver.

The cause behind this is this [piece of code](https://github.com/scylladb/scylla-rust-driver/blob/fd06928929c0dd78a72c7aca494a998da1514a79/scylla-macros/src/from_user_type.rs#L63): 
```rs
 if fields_iter.next().is_some() {
    return Err(FromCqlValError::BadCqlType);
}
```

That is why we're using our own version of scylla-macros, but I think it would be better letting the user choose if they want to allow this kind of behavior. 

I think there could be two solutions:
1. The easiest would be just to duplicate this derive macro with a different name with the check disabled and a different name.
  - Pros: 
    -  Easier
  - Cons:
    -  Duplicate Code
    -  Less user-friendly

2. Add a #[scylla(non_exhaustive)] derive macro attribute at the struct level for FromUserType.
  - Pros:
    -  Easier to use
    -  Cleaner code
  - Cons: 
    -  A little bit harder to implement

What do you think of these two approaches ? 
Do you think it would be worth adding them to this crate ?

**Comment by wprzytula** [comment]
Ref: #962

**Comment by wprzytula** [comment]
The PR with new deserialization macros has been merged (https://github.com/scylladb/scylla-rust-driver/pull/1024), but the new deserialization API they generate implementation for is not yet available in the driver. For tracking it, see https://github.com/scylladb/scylla-rust-driver/issues/462.
