### ISSUE TITLE
UDTs require useless information

### ISSUE THREAD

**Issue by Ponewor** [scylladb/scylla-rust-driver#433]
`CqlValue::UserDefinedType` contains fields `keyspace` and `type_name` that are useless. They are not used during serialization.

The user can make a CQL query just by typing the actual UDT value but if he wants to use driver's `CqlValue::UserDefinedType` he needs to additionally come up with some `keyspace` and `type_name`. It's even worse than that - it's not obvious at the first glance that those values actually do not matter, so the user may believe that he has to know them.

It is easy to fix but not without breaking the existing API. What do you think?

**Comment by psarna** [comment]
On the other hand, perhaps it makes the mechanism a little less error-prone - as in, users would explicitly see which type (defined by its keyspace and name) they are filling. **If** other drivers also ignore keyspace and type_name, we should follow suit. If they don't, it's probably better to remain compatible with the de-facto standard. Let's check a few other drivers (e.g. golang and Java)

**Comment by avelanarius** [comment]
@Lorak-mmk is (part of it) it still relevant after serialization refactor?
