### ISSUE TITLE
Make topology/metadata fetch failures non-fatal

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#438]
Ref: https://github.com/scylladb/scylla-rust-driver/issues/437#issuecomment-1106568501

Currently, the driver fetches topology and schema information (we call it metadata) on Session creation and fails if an error occurs during fetching/parsing of that data - which is undesirable, because most of the metadata is not critical for the driver to work. It may fail for various reasons, e.g. due to a bug (like in https://github.com/scylladb/scylla-rust-driver/issues/437), nonstandard data in the system tables in a format not supported by the driver or connection errors.

To avoid issues like https://github.com/scylladb/scylla-rust-driver/issues/437, we need to let the driver ignore some errors during automatic metadata fetch.

Things to figure out:

- Which parts of the metadata are required, and which can be ignored on error? For example, the driver doesn't use schema information internally (yet?) so it might be safe to skip, on the other hand topology information is important for correct routing.
- How other drivers are handling this?

**Comment by psarna** [comment]
I think that failing to fetch correct information for routing is also acceptable. The driver is perfectly capable of running without any topology information thanks to fallback policies, so aside from issuing a warning, we should continue operating as if fetching succeeded.
