### ISSUE TITLE
"No connections in the pool" error when one forgets to specify username/password and tries to run a query

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#443]
When scylla is configured to require username/password but the user doesn't configure username/password in the driver, session creation succeeds but apparently no connections are being made. This results in a confusing error which does not indicate the source of the problem (which the driver probably should be able to detect).

Minimal reproducer:

```rust
use anyhow::Result;
use scylla::transport::session::Session;
use scylla::SessionBuilder;

#[tokio::main]
async fn main() -> Result<()> {
    let session: Session = SessionBuilder::new()
        .known_node("127.0.0.1")
        .build()
        .await?;
    println!("Connected");

    session.query("SELECT * FROM system.local", &[]).await?;
    println!("Ran query");

    Ok(())
}
```

Scylla node should be run with parameter `--authenticator org.apache.cassandra.auth.PasswordAuthenticator`.

Output:

```
Connected
Error: IO Error: No connections in the pool. Pool status: Broken
```

**Comment by piodul** [comment]
This also happens when the username/password combination is incorrect.

**Comment by jcswart** [comment]
I also see this issue if the node is not reachable. In the above example if the driver attempts to connect to `127.0.0.1` and no such node exists -- the session will build none the less.

I believe this is a result of https://github.com/scylladb/scylla-rust-driver/issues/438 , in the past with `0.2.1` bad config would cause the Session building to fail. Now it seems "there is no such thing as bad config" to the driver.

If you pass in invalid config you can see the driver internally failing to do anything via tracing, but your application sees a valid Session until you try to use it.

Essentially neither `Session::connect` nor `SessionBuilder::build` can tell you if the session was created successfully. You need to manually execute a query to such as `refresh_metadata` to see if your `Session` is valid.

Perhaps I am doing something wrong?

**Comment by psarna** [comment]
We indeed changed the session to be more lenient if it can't fetch metadata, because up-to-date metadata isn't strictly necessary for the driver to work correctly. Pre-#438, we indeed piggy-backed on the metadata fetching mechanism to also validate if a session is functional, but right now we know it may be too strict, and some users would prefer to be able co continue using the driver, even if metadata can't be fetched. Using `refresh_metadata` or any other query sounds like a good workaround if you want to do an additional check that the session is valid.

**Comment by jcswart** [comment]
Thank you for the response. I appreciate the work you are doing.

**Comment by philipdaquin** [comment]
Hey, thank you for this post. This is what worked for me:
````

/// If a database already exists then we simply connect to that
async fn connect_to_existing_db() -> Result<Session> { 
    let hostnode = KnownNode::Hostname(SCYLLA_URL.to_string());
    let (auth_username, auth_password) = ( 
        Some(USER.to_string()), Some(PASSWORD.to_string()));
    let cfg = SessionConfig::new();
    let cfg =  SessionConfig { 
        known_nodes: vec![hostnode],
        auth_username,
        auth_password
        ,..cfg
    };  

    let existing_session = Session::connect(cfg).await?;
    existing_session.use_keyspace(KEYSPACE_NAME.as_str(), false).await?;

    Ok(existing_session)
}
`

```

**Comment by TeemuKoivisto** [comment]
Yeah uhh I think this error should be more granular. I spent hours trying to figure out whether I had configured something wrong with my proxies and whatnot only to realize I was missing `.user("cassandra", "cassandra")` from my SessionBuilder.
