### ISSUE TITLE
Driver performance degradation with TokenAwarePolicy when (nodes < RF)

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylla-rust-driver#452]
https://github.com/scylladb/scylla-rust-driver/blob/652f1314503f4adc4aaf074b407b234970297fa7/scylla/src/transport/load_balancing/token_aware.rs#L26-L29

Scrutinize the above. Usually (when nodes >= RF) the above ends after just a few iterations. Since tokens are distributed between nodes randomly, we will quickly find RF unique nodes. But if the number of nodes in the ring is below RF, this code will iterate over *all* tokens, which takes significant work.

I bumped into this during a benchmark. It caused the driver to spend more than 50% of its CPU time in `plan()` when driving a 2-node cluster with RF=3.

**Comment by piodul** [comment]
Good catch. Looking at the code of `network_topology_strategy_replicas` I suspect we might have a similar problem with NetworkTopologyStrategy, too (but not 100% sure, didn't try to reproduce).

@havaker is refactoring load balancing right now (https://github.com/scylladb/scylla-rust-driver/pull/449), so I think we should either fix it during or after the refactor.

**Comment by havaker** [comment]
Fixed in #612.
