### ISSUE TITLE
Driver panics when a Result could be returned

### ISSUE THREAD

**Issue by junglie85** [scylladb/scylla-rust-driver#467]
I recently had an application crash with the following error messages, which I could have recovered from.

```
Error: Cannot persist to storage: Database returned an error: The query is syntatically correct but invalid, Error message: Batch too large
```

and

```
Error: Database returned an error: Not enough nodes responded to the read request in time to satisfy required consistency level (consistency: LocalQuorum, received: 0, required: 2, data_present: false), Error message: Operation timed out for my_keyspace.my_table - received only 0 responses from 2 CL=LOCAL_QUORUM
```

It would be helpful if the driver returned `Result`'s instead of panicing on errors.

**Comment by psarna** [comment]
Queries do return results though (`Result<QueryResult, QueryError>`), we don't `unwrap()` anywhere in the code unless the result is guaranteed to be a non-error. If we did `unwrap()` somewhere, it's a bug that we should fix, but I can't judge that before I see the call site - do you have any links to the code that failed for you?

**Comment by junglie85** [comment]
Let me tripple check that I'm not `unwrap()`ing somewhere.

**Comment by junglie85** [comment]
Okay, I can't repro that anymore. I'll make an assumption that it was my mistake and go ahead and close this issue.
