### ISSUE TITLE
Handle properly rpc_address set to 0.0.0.0 in the control connection host

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#490]
### Problem
Currently, the driver assumes that `rpc_address` is properly set and uses that address as peer address for `known_host` regardless of its validity. This caused #487. Before merging #471 the `rpc_address` would be substituted for the initially provided address, hence the problem was not visible before.
Moreover, basic AWS configuration of Scylla sets `rpc_address` to `0.0.0.0`.

### Proposed solution
1. At least, we should emit a warning / an error, saying that the address was misconfigured, leading to failure in connecting to that node as coordinator.
2. We could fall back to the provided contact point (`known_host` address). This would prevent losing connectivity to that node, yet would not support address translation (or at least be tricky).
3. We could use `broadcast_rpc_address` if `rpc_address` is invalid, or even try using `listen_address`.

As it's a silent-yet-serious bug, I think we should consider it urgent.

**Comment by wprzytula** [comment]
On AWS, `broadcast_rpc_address` is set to a correct address by default, but this information is not present in `system.local` table. While it seems that it is present as `rpc_address` column of each entry in `system.peers` table, there is no guarantee that there exist any peer (cluster can be single-node). Therefore we can't always fetch `broadcast_rpc_address` from the cluster.

**Comment by psarna** [comment]
@wprzytula Cassandra's (and Scylla's) configuration for addresses is rather complex, and described thoroughly here: https://www.instaclustr.com/blog/demystifying-cassandras-broadcast-address/ . In general, one should try using `rpc_address`, and if it's set to `0.0.0.0`, one should fall back to `broadcast_rpc_address`, which will hold a correct address. I do not remember what's the current heuristics in the driver after your change, I'll check it in a minute, but if the pattern is different, we need to change it. Both rpc_address and broadcast_rpc_address are present as columns in system.local.

Here's the comment from scylla.yaml regarding `rpc_address`:
```yaml
# Note that unlike listen_address, you can specify 0.0.0.0, but you must also
# set broadcast_rpc_address to a value other than 0.0.0.0.
rpc_address: localhost
```

**Comment by wprzytula** [comment]
@psarna 
`system.local` contains `broadcast_address` and not `broadcast_rpc_address`. Following Scylla's docs, `broadcast_address` is related to `listen_address` and not `rpc_address`.

**Comment by psarna** [comment]
Ugh, I kept actually seeing `_rpc_` in there, my mind playing tricks on me. You're right, sounds problematic. In that case, maybe we should consider an ugly trick of falling back to `broadcast_address` if `rpc_address` is equal to 0.0.0.0 and is thus not reachable.

**Comment by piodul** [comment]
Maybe we could change the address translator to receive multiple addresses, some of them optional? We could give it `connect_address` (used to establish the control connection), `broadcast_rpc_address`, `rpc_address` - some (or all) could be `Option`. If the translator sees a non-`None` `connect_address`, it will be allowed to return it directly, bypassing the problem with the address in `system.local`. It will also be free to do otherwise if the address is calculated in another way (e.g. doesn't use IPs at all).

**Comment by wprzytula** [comment]
> We could give it `connect_address` (used to establish the control connection), `broadcast_rpc_address`, `rpc_address` - some (or all) could be `Option`.

We _can't_ give the address translator `broadcast_rpc_address`, because we have no access to it.


> Ugh, I kept actually seeing `_rpc_` in there, my mind playing tricks on me. You're right, sounds problematic. In that case, maybe we should consider an ugly trick of falling back to `broadcast_address` if `rpc_address` is equal to 0.0.0.0 and is thus not reachable.

Why fall back to `broadcast_address` and not `connect_address`? It seems more logical that if we managed to contact the node on that address, it should remain valid; conversely, `broadcast_address` can be an inner address, hidden in a private network of one's datacenter (while the `broadcast_rpc_address` concerns the public address for client connections).

I would strongly opt for **either** adding `broadcast_rpc_address` to `system.local` table **or** falling back to `connect_address`. After all, `connect_address` is at least guaranteed to point to some node (but perhaps a different one every time because of some load balancer...).

Keep in mind that the most important is to prevent the __silent__ bug that disables one node. So if we put the burden of handling this problem on the address translator, what should we do in situation when there's no address translation providing? A simple fallback with a warning emitted?
