### ISSUE TITLE
Bug: driver never retries on Response::Error

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#501]
### Problem:
When driver receives a response of type `Error` (e.g. `ServerError` or `Overloaded`), it prints "_Query succeeded._" and never retries, but the error is returned instantly (as if `FallthroughRetryPolicy` was used).

### Steps to reproduce:
Forge an error response frame for driver's request.

### Found cause:
In `Session:execute_query()` the `Option<QueryResponse, QueryError>` holds `Response::Error` as `Ok` and not `Err` variant, so pattern matching leads to returning that as successful result.

### Proposed solution:
Get rid of `Response::Error` variant and make the aforementioned `Option` hold `Error` response as `Err(QueryError)` variant.

#496 contains the proposed fix.

**Comment by psarna** [comment]
again, let's extract the fix out of #496 and merge it separately
