### ISSUE TITLE
Implement downgrading consistency retry policy

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#503]
While downgrading consistency retry policy is generally deprecated among drivers (https://github.com/datastax/python-driver/blob/9a645c58ca0ec57f775251f94e55c30aa837b2ad/cassandra/policies.py#L895-L910) and not recommended unless really sure about all its pitfalls, there are some valid use cases for the policy, so let's implement it.

**Comment by wprzytula** [comment]
I believe that implementing such a policy requires some breaking changes in `RetryDecision` struct: it must contain also new CL info:
```
pub enum RetryDecision {
    RetrySameNode(Consistency),
    RetryNextNode(Consistency),
    DontRetry,
}
```
...and driver shall respect that CL during retries.
Do you agree with that? @psarna @cvybhu

**Comment by psarna** [comment]
I thought about that and I also suspected we need to extend the generic struct for handling this policy - I'm fine with that, it's only effectively used internally

**Comment by wprzytula** [comment]
The change will affect users that have implemented their own `RetryPolicy`, but I guess we suggest them dealing with that. After all, the change will only require them to reuse the CL received in `QueryInfo`.
BTW, what shall a policy do in case of `LegacyConsistency::Serial(_)` being returned?
