### ISSUE TITLE
Implement latency-aware load balancing policy

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#505]
Other drivers deliver a latency-aware policy, e.g. https://docs.datastax.com/en/developer/cpp-driver/2.7/topics/configuration/#latency-aware-routing

The policy tracks and estimates latency for all nodes and tries to pick a node which should perform better than others.

**Comment by piodul** [comment]
Probably related to: https://github.com/scylladb/scylla-rust-driver/issues/260

**Comment by piodul** [comment]
Done in https://github.com/scylladb/scylla-rust-driver/commit/ba142e515ef44771587b2029a4a527e014140029
