### ISSUE TITLE
Remove lines starting with `#` when generating documentation book

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#521]
The documentation book is written in the mdbook format.

One feature of mdbook syntax is that lines starting with `#` are not shown in code blocks.

We need to remove them because they show up in the official docs:
![image](https://user-images.githubusercontent.com/36861778/185448905-ee308818-115f-48b2-a18a-e9cdd73c59e9.png)

This makes the examples much more confusing that they should be.

**Comment by psarna** [comment]
Sounds like what we should actually do is fix the official docs generation scripts to also ignore these lines

**Comment by cvybhu** [comment]
:+1: Yeah by 'remove them' I mean add something like `remove_sphinx_markdown` in https://github.com/scylladb/scylla-rust-driver/blob/main/docs/build_book.py

**Comment by cvybhu** [comment]
Oh there already is https://github.com/scylladb/scylla-rust-driver/blob/main/docs/_utils/drop_hashes.py, but it isn't used by any workflow
