### ISSUE TITLE
Prepared Statement with IN operator

### ISSUE THREAD

**Issue by krzysztofgal** [scylladb/scylla-rust-driver#539]
Is it possible to bind multiple values to `SELECT ... IN (?)`. Have seen (maybe) that Java cassandra driver have support for this.
When I provide values `ids: Vec<Uuid>` in form `(&ids,)` then i get `marshaling error: Validation failed for uuid - got 84 bytes`. When use `&ids` directly then I get error `Invalid amount of bind variables: expected 1 received 4`

**Comment by piodul** [comment]
Try dropping the parentheses around the question mark:

```cql
SELECT ... IN ?
```

**Comment by krzysztofgal** [comment]
That was embarrassing case of "I would never think of it". Its working, thanks.
