### ISSUE TITLE
Immediately fetch new topology data after schema changes

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla-rust-driver#544]
When there is a schema altering query (`CREATE KEYSPACE`, `DROP TABLE`, ...) the driver automatically awaits schema agreement to make sure that the created entity can be used on any node.

Queries like `CREATE KEYSPACE` affect load balancing, but new topology information is not fetched immediately. The queries will be sent to the wrong nodes until the new information is fetched by periodic topology updates (60s (!)).

We could call `refresh_metadata` inside `handle_auto_await_schema_agreement` to fix this.

Pros:
* Load balancing chooses the right nodes as soon as possible, important in benchmarks
* Tests that handle metadata information don't require calling `refresh_metadata` immediately

Cons:
* Performance problems?

**Comment by piodul** [comment]
@Gor027 is probably working on this right now, it's needed for https://github.com/scylladb/cpp-rust-driver/pull/72 .

Schema altering queries are rather rare so fetching the full metadata shouldn't be a big problem. The response to a schema altering query contains information what was changed by the schema, so perhaps we could optimize this later and only fetch information on the control connection about the changed items.

**Comment by wyfo** [comment]
> We could call refresh_metadata inside handle_auto_await_schema_agreement to fix this.

Does it means that when several schema-related queries are made successively, `refresh_metadata` would be called for each of them successively?

**Comment by Gor027** [comment]
I have tested the approach described in the above comment in the `cpp-rust` bindings with `CassandraTypesTests.UDT` test which creates a new user-defined type and then tries to get information about it from the keyspace metadata. The schema metadata is being refreshed with a little delay because of `tokio::select` in `ClusterWorker::work()` which picks a branch randomly.
