### ISSUE TITLE
Remove BatchResult in favor of QueryResult

### ISSUE THREAD

**Issue by devrandom** [scylladb/scylla-rust-driver#554]
`BatchResult` is really the same as ~~`QueryResponse`~~ `QueryResult`, except that the `response` field is dropped.  This makes it impossible to get at the `[applied]` bools, and therefore the caller can't tell if the batch wasn't applied because it had any failing conditions.  `Session::batch` should just return `QueryResult` instead.

(changed description to refer to `QueryResult`, because a query error is not possible for a batch return value)

**Comment by cvybhu** [comment]
`Session::batch` returns a result, which indicates whether the batch succeeded.

```rust
    pub async fn batch(
        &self,
        batch: &Batch,
        values: impl BatchValues,
    ) -> Result<BatchResult, QueryError> {
```
If the batch was applied successfully it will return `Ok(BatchResult)`, otherwise it's gonna be `Err(QueryError)`.

> [applied] bools

Could you clarify which bools you would like to access?

**Comment by devrandom** [comment]
When a batch has failing conditions, it doesn't error, it returns a `Response::Result`, as it should.  The result's first column is `[applied]`, and the value in that column is set to false (i.e. "batch not applied") if the condition is false anywhere in the batch.

demonstrating this with a manual cqlsh example:
```
cqlsh:ks> BEGIN BATCH
UPDATE ks.data set version = 1 WHERE key = 'x1a' and client = 0x01 IF version = 0;
UPDATE ks.data set version = 1 WHERE key = 'x1b' and client = 0x01 IF version = 0;
APPLY BATCH;

 [applied] | client | key | version
-----------+--------+-----+---------
     False |   0x01 | x1a |       1
     False |   0x01 | x1b |       0
```

When running this with a breakpoint inside `Session::batch`, I do see the right values in the `QueryResponse`, but it's thrown away when constructing the `BatchResult`.

**Comment by devrandom** [comment]
BTW, the schema for the above is `CREATE TABLE IF NOT EXISTS ks.data (client blob, key varchar, version bigint, value blob, primary key (client, key))` if that helps.

**Comment by devrandom** [comment]
I updated the issue description above to clarify this is about batches with failing conditions, not about other errors.

**Comment by cvybhu** [comment]
Ah this looks like it's because of #100.
This should be finally fixed, I will take a look at it, thank you for reporting.

We can't just replace `BatchResult` with `QueryResponse` because the response can also contain an error, and the `Result<>` would always be `Ok()`, but we might be able to retain the `applied` fields during conversion.

**Comment by devrandom** [comment]
I'm not sure I understand the second part.  The signature of `batch` is:

```rust
    pub async fn batch(
        &self,
        batch: &Batch,
        values: impl BatchValues,
    ) -> Result<BatchResult, QueryError> {
```

I'm suggesting replacing the result line with:

```
    ) -> Result<QueryResponse, QueryError> {
```

So if there is a real error, you'd return `Err(QueryError)`, and if there is a false condition, you'd return `Ok(QueryResponse)` and figure out there was a false condition from the `[applied]` flags.

Alternatively, you could wrap `QueryResponse` such as:

```rust
struct BatchResult(pub QueryResponse)
```

and add `BatchResult::is_all_applied()` to summarize the `[applied]` flags.  This could be a nicer API for some use cases.

Note that the rest of the columns in the returned `QueryResponse` are useful, because they give the caller the current state of the rows in question **in the database**, so I still wouldn't throw them away.
