### ISSUE TITLE
 warning="This query should use ALLOW FILTERING and will be rejected in future versions."

### ISSUE THREAD

**Issue by ajosecueto** [scylladb/scylla-rust-driver#587]
I'm using MV and making a query based on primary key logs that message.

```rust
let prepared: PreparedStatement = self
            .session
            .prepare("SELECT * FROM signup.by_username WHERE username = ?")
            .await?;
```

**Comment by piodul** [comment]
The message is generated by the database, not the driver. This is most likely not an issue with the driver, but rather with the database itself.

Please post a question about the problem on the ScyllaDB User Slack (https://slack.scylladb.com/) or create an issue on the ScyllaDB's issue tracker (https://github.com/scylladb/scylladb/issues).
