### ISSUE TITLE
`Datacenter` struct not exported.

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/scylla-rust-driver#618]
Struct `Datacenter` defined here: https://github.com/scylladb/scylla-rust-driver/blob/f145ceaa2403f4fc537a0f5c1865995d230c1bda/scylla/src/transport/cluster.rs#L54-L58 is not exported in transport's mod.rs, which makes it's documentation inaccessible (https://docs.rs/scylla/latest/scylla/transport/struct.ClusterData.html - can't click it the return type of [get_datacenters_info](https://docs.rs/scylla/latest/scylla/transport/struct.ClusterData.html#method.get_datacenters_info)).

**Comment by wprzytula** [comment]
Ref #977

**Comment by muzarski** [comment]
Closing since https://github.com/scylladb/scylla-rust-driver/pull/1094 was merged
