### ISSUE TITLE
`execute_iter`/`query_iter` error on `UPDATE` or `INSERT` query.

### ISSUE THREAD

**Issue by 0e4ef622** [scylladb/scylla-rust-driver#631]
It would be more reasonable if it returned an empty iterator. Instead, I get `ProtocolError("Unexpected response to next page query")`.

**Comment by wprzytula** [comment]
@piodul WDYT?

**Comment by piodul** [comment]
Although the `_iter` methods are not really meant for sending such queries, I think we change the behavior to what the issue proposes - I don't see a reason against this.
