### ISSUE TITLE
Make address translation happen only upon opening new connection

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#640]
### Motivation
The logical route to a node being subject to address translation might undergo frequent changes. For instance, an IP of a proxy that the node resides behind may change. The user-provided `AddressTranslator` instance may handle this situation correctly, and this is good. However, the driver's implementation forces `Node` struct to be immutable, disallowing for adjusting the change inside `Node.address` field. To mitigate the problem, we recreate the `Node` instance if its translated IP changes. This necessarily leads, however, to recreation of the whole `NodeConnectionPool` and establishing all connections once again.

The issue is especially detrimental in case of Serverless, where a new DNS query is issued for each peer upon Metadata query, in order to get current address of proxy in the node's DC. Then, we likely receive a different IP each time (thanks to DNS round robin, for example), which leads to the recreation of node connection pool described above. This behaviour was observed during tests on serverless cluster.

### Proposed solution
Move address translation from Metadata query (`query_peers()`) to `PoolRefiller::start_opening_connection()`. This way, `Node` struct will not require any alterations if only a translated address changes.
In case of Serverless, a proxy of one DC will have a single `NodeConnectionPool` and `PoolRefiller`, which will contact it through possibly multiple IPs.

**Comment by wprzytula** [comment]
Work on this is being done, a PR will be opened shortly.

**Comment by mykaul** [comment]
@wprzytula quick question - if DNS returns *multiple* address (and indeed, in different order), shouldn't we walk over all addresses and store them?

**Comment by wprzytula** [comment]
> @wprzytula quick question - if DNS returns *multiple* address (and indeed, in different order), shouldn't we walk over all addresses and store them?

We could, but how would we benefit from it?

**Comment by mykaul** [comment]
> > @wprzytula quick question - if DNS returns _multiple_ address (and indeed, in different order), shouldn't we walk over all addresses and store them?
> 
> We could, but how would we benefit from it?

You'd connect to all its IPs, instead of only some of them? (long term, MPTCP could be cool, but that's futuristic)
