### ISSUE TITLE
Session execute spends 30% of its time allocating prepared_id for tracing (even if disabled)

### ISSUE THREAD

**Issue by Ten0** [scylladb/scylla-rust-driver#655]
This:
https://github.com/scylladb/scylla-rust-driver/blob/28b5c1d14e43e8c1487fddbae9d393d7b94b3979/scylla/src/transport/session.rs#L893

Shows in my benchmarks as taking 36% of the CPU usage of `Session::execute`:
![image](https://user-images.githubusercontent.com/9094255/224496131-5547c0eb-f723-4fdb-9284-9457e68b6fc5.png)

which seems to be a lot for probably-disabled tracing purposes.

I haven't enabled any particular tracing option, yet this still shows in my benchmark.

NB: `trace_span` seems to work even if prepared_id is provided as [format_args!](https://doc.rust-lang.org/stable/std/macro.format_args.html) instead of [format!](https://doc.rust-lang.org/stable/std/macro.format.html), which would probably be more idiomatic (don't forget to remove the as_str to not hit [this one](https://doc.rust-lang.org/stable/std/fmt/struct.Arguments.html#method.as_str)), but I doubt this would change much in this case because `trace_span` should be expanded before `format`.

**Comment by Ten0** [comment]
Update: actually this does change a lot:
I've benchmarked with format_args, and:
![image](https://user-images.githubusercontent.com/9094255/224502112-05005b1d-d0fb-42d0-8dd7-a11556fbaf3f.png)

My guess is, since the `if`s don't change, this means either `tracing` is making a check on whether we should log further down than the macro call, or it's using some kind of arena to store its traces, so just the rendering of the id does not allocate.

In any case, PR incoming...

**Comment by piodul** [comment]
Which tracing subscriber are you using? I vaguely remember that I once looked at flamegraphs of my own benchmarking application and I saw that arguments for trace level messages were evaluated even though they were not disabled. I think I was using [`env_logger`](https://docs.rs/env_logger/latest/env_logger/) which was originally meant for the `log` ecosystem, but `tracing` makes it automatically work. I dug into the implementation and AFAIR the compatibility layer causes the `trace!` macro to always think that the trace level is enabled, so it always evaluated the arguments even if they were discarded later.

All in all, the PR will definitely be useful - I originally dismissed the issue as a necessary performance cost of enabling tracing, but you have shown this not to be the case. Thanks.

**Comment by Ten0** [comment]
Using log (fern), but not with a low enough level that it would show any message while that cost was there regardless.
