### ISSUE TITLE
Re-add LWT routing optimization

### ISSUE THREAD

**Issue by havaker** [scylladb/scylla-rust-driver#672]
LWT routing optimization was dropped in https://github.com/scylladb/scylla-rust-driver/pull/612 to decrease the scope of that pull request. It needs to be brought back.

Ref: #100

**Comment by wprzytula** [comment]
LWTs are actually supported at the moment; what still needs to be added is the LWT load balancing optimisation in `DefaultPolicy`. Please adjust the issue's name and description accordingly.
