### ISSUE TITLE
Make it possible to nest FromCqlValError

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#702]
`FromCqlValError` is quite a limited error type that doesn't allow to express too many failure scenarios. However, we can improve it slightly by making it possible to nest it. The use case is to report errors from compound types, e.g. UDTs.

Proposed extension:

```rust
pub enum FromCqlValError {
    //...

    // New variant
    #[error("{message} with error {err}")].
    BadCqlVal {
        err: Arc<FromCqlValError>,
        message: String,
    }
}
```

**Comment by roydahan** [comment]
Is this still on-track / planned for MS 0.13.0?

**Comment by wprzytula** [comment]
> Is this still on-track / planned for MS 0.13.0?

I'm not sure if we want to invest into `FromCqlValError`, because it's part of the old deserialization framework, which will shortly be deprecated anyway. The respective errors for the new framework are going to be designed in a more flexible way.

**Comment by Lorak-mmk** [comment]
This is no longer relevant with new deserialization framework.
