### ISSUE TITLE
Update suggested dependencies in quickstart docs

### ISSUE THREAD

**Issue by havaker** [scylladb/scylla-rust-driver#706]
https://github.com/scylladb/scylla-rust-driver/blob/1ffb8495defd38e4369d7974ed74ecc33540be75/docs/source/quickstart/create-project.md?plain=1#L10-L18

Docs are recommending installation of `scylla = "0.4"`, but describing the API of `scylla = "0.8"`.

**Comment by wprzytula** [comment]
This is a duplicate of #670.

**Comment by piodul** [comment]
If it is a duplicate, then it can be closed. I'm doing it right now.
