### ISSUE TITLE
Proper handling for named serialized values in batches

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#711]
Currently, named serialized values provided in batches are not handled properly. They are reported to ScyllaDB as unnamed serialized values, which have slightly different encoding. In the best case, this results in a parse error on the Scylla side.

It's not really possible to implement support for it properly due to the limitations of the protocol. In `QUERY` and `EXECUTE`, there is a `<flags>` field which contains a bit that determines whether serialized values that follow are named or not. However, for `BATCH`, the `<flags>` field is placed _after_ all serialized values. There are some problems with that:

1. Due to how the protocol is organized, the elements of the serialized frame must be parsed in order. Therefore, serialized values are parsed before the `<flags>` field, even though its "with names for values" bit controls how the serialized values are supposed to be parsed. Effectively, the bit is ignored because it is impossible to support it. This is the case both in ScyllaDB and Cassandra - see https://issues.apache.org/jira/browse/CASSANDRA-10246.
2. Even if the bit were supported, it is supposed to affect serialized values of all statements in the batch, so this causes problems if named/unnamed serialized values are mixed.

There are some things that we could do:

- Reject named serialized values in batches. They result in improperly encoded requests which can result in parse error (most likely) or a mis-parsed request (if unlucky) - so this is a bug that should be fixed.
- In case of prepared statements, rewrite named serialized values to unnamed serialized values and then send. There are some drawbacks to this. It incurs a slight performance penalty which would otherwise be paid on the server side. We can only do it for prepared statements because we need prepared statement metadata for this. Therefore this sounds more like a workaround than a proper fix.
- Consider extending the protocol ourselves. The Cassandra issue was reported over 7 years ago and is present at least since protocol version v3 up to v5 (however, it looks like it was put under a new umbrella issue yesterday: https://issues.apache.org/jira/browse/CASSANDRA-18478) - so it's hard to tell when it will be fixed. We already provide some extensions to the CQL protocol that a driver needs to opt-in and we might consider doing so here as well. This would require adjustments both on the ScyllaDB side and the driver side, so it's a bigger effort.

**Comment by Keshi** [comment]
I just ran into this issue in production.  We are using named serialized values for correctness and maintainability reasons, and some of the queries need to go into a batch, and have been resulting in a fairly unhelpful truncated frame error.
I didn't recall seeing any documentation of these limitations in the rust scylla docs, and would probably be a helpful addition since it is not enforced at compile time.

I think that if #2 not super hard to do, even if it is not ideal, it would still be a very welcome addition until there is a better/real solution.  Given its limitation, perhaps #1 for unprepared queries, and #2 for prepared queries would be welcome.

**Comment by Lorak-mmk** [comment]
After serialization refactor, the driver no longer sends named values. It also no longer sends unprepared queries with any values. Basically, solution 2 was implemented, but with a change: unprepared queries with values are silently prepared by a driver, so this is a proper fix on the driver side, not a temporary workaround.
