### ISSUE TITLE
Driver does not support f64

### ISSUE THREAD

**Issue by tapiocaboy** [scylladb/scylla-rust-driver#732]
Hey Guys
We are using Scylla driver with Cassandra
The observation which me made after running the test
Seems its does not support i64 or f64
Is there a workaround for this ?

```
thread 'tests::tests::test_is_valid_account' panicked at 'called `Result::unwrap()` on an `Err` value: DbError(Invalid, "Expected 4 or 0 byte int (8)")'
```

```
pub async fn update_balance(&self, account: &Account) -> Result<(), Error> {
        let balance: f64 = 1.0;
        self.session
            .query(
                "UPDATE l1x.account SET balance = ? WHERE address = ?;",
                (&balance, &account.address),
            )
            .await
            .unwrap();
        Ok(())
    }
```

**Comment by piodul** [comment]
It looks like you are trying to send an eight-byte floating point value `f64` in the place of CQL `int` column, which is a four-byte integer. The driver doesn't support such conversions, the type has to match directly. In your case I think you should use `i32` instead.

You can see the current mapping between Rust and CQL types here: https://rust-driver.docs.scylladb.com/stable/data-types/data-types.html
