### ISSUE TITLE
Query Syntax: Appending to a HashMap

### ISSUE THREAD

**Issue by WarrenN1** [scylladb/scylla-rust-driver#739]
In Cassandra, a Hashmap can be appended to/updated via the following CQL query:
```
UPDATE cycling.cyclist_teams SET teams = teams + {2009 : 'DSB Bank - Nederland bloeit'} WHERE id = 5b6962dd-3f90-4c93-8f61-eabfa4a803e2;
```
How would I go about doing this via the Rust API? Would it be:

```
session.query("UPDATE cycling.cyclist_teams SET teams = teams + {? : ?} WHERE id = 5b6962dd-3f90-4c93-8f61-eabfa4a803e2, (2009, 'DSB Bank - Nederland bloeit'));
```
or
```
hashmap.Insert(2009, 'DSB Bank - Nederland bloeit')
session.query("UPDATE cycling.cyclist_teams SET teams = teams + {? : ?} WHERE id = 5b6962dd-3f90-4c93-8f61-eabfa4a803e2, (hashmap,));
```

**Comment by piodul** [comment]
Each value in the tuple correspond to one bind marker (question mark) in the query string.

Your first example will work if you change the single quote marks to double quote marks (it's not a valid Rust syntax for string literals):

```rust
session.query("UPDATE cycling.cyclist_teams SET teams = teams + {? : ?} WHERE id = 5b6962dd-3f90-4c93-8f61-eabfa4a803e2", (2009, "DSB Bank - Nederland bloeit")).await?;
```

In the second example, instead of `{? : ?}` you should just use `?` - because the hashmap you pass in is a single value:

```rust
let mut hashmap: HashMap<i32, &str> = HashMap::new();
hashmap.insert(2009, "DSB Bank - Nederland bloeit");
session.query("UPDATE cycling.cyclist_teams SET teams = teams + ? WHERE id = 5b6962dd-3f90-4c93-8f61-eabfa4a803e2", (&hashmap,)).await?;
```

**Comment by piodul** [comment]
Next time, in case of general questions, please post them on the [ScyllaDB Forum](https://forum.scylladb.com/) or the #rust-driver channel on the [ScyllaDB Users Slack](http://slack.scylladb.com/). GitHub issues should be used for tracking bugs, feature requests, requests to update the documentation - generally, things that ultimately result in some pull requests being merged.

I'm closing this issue.
