### ISSUE TITLE
Json Support: Parsing JSON from SELECT statement

### ISSUE THREAD

**Issue by WarrenN1** [scylladb/scylla-rust-driver#744]
Given Scylla allows inserting JSON, how do we handle JSON via the rust driver? I don't see anything pre built in the package to handle it?

**Comment by piodul** [comment]
What kind of support exactly do you have in mind?

If you mean this: https://docs.scylladb.com/stable/cql/json.html , then it doesn't require any additional support from the driver. You just insert or select JSON as a string and the DB does serialization/deserialization itself.

For example:

```rust
// Schema:
// CREATE TABLE IF NOT EXISTS ks.t (a int, b int, c text, primary key (a, b))

// Inserting
let json_payload = "{\"a\": 123, \"b\": 456, \"c\": \"zxcvbnmn\"}";
session
    .query("INSERT INTO ks.t JSON ?", (json_payload,))
    .await
    .unwrap();

// Selecting
let rows = session
    .query("SELECT JSON a, b, c FROM ks.t", ())
    .await
    .unwrap()
    .rows_typed::<(String,)>()
    .unwrap();

for row in rows {
    println!("row: {}", row.unwrap().0);
}
```

**Comment by Lorak-mmk** [comment]
Closing because of no response. It also seems there is nothing to do for us here as @piodul said.
