### ISSUE TITLE
Driver-side metrics

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla-rust-driver#75]
We should gather and expose some metrics about driver operations, e.g. how many queries were sent, how many of them resulted in an error, what was their latency, etc.

Implementation detail: @piodul since session is immutable, what's the rusty way of keeping mutable metrics inside it? RefCell?

**Comment by kbr-** [comment]
When I was working on the topology refreshes I had a thought that this could be done in a more efficient way -- with less synchronization -- if Session query/prepare/execute would take a mutable reference to the Session. I.e. we have a guarantee that there's only one user of Session at a time.

We could then make Sessions `Clone`able and the clones could share some data structures (e.g. connections). But Sessions know their own internals so they can do the sharing more efficiently.
