### ISSUE TITLE
Add a test for wrong/missing named bind markers in prepared statement

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla-rust-driver#759]
This request is actually about testing scylla itself and not RUST driver.
It is related to the scylla issue of: https://github.com/scylladb/scylladb/issues/12727
Since the fix of this issue cannot be tested via python-driver and unit-test, one (possibly not-too-complicated) alternative is using a RUST driver unit test.

see more details and an example reproducer in the above [scylla issue](https://github.com/scylladb/scylladb/issues/12727#issuecomment-1416253781).

**Comment by piodul** [comment]
I'd rather not put a test which verifies behavior of Scylla here. This is far from a perfect solution:

- We might improve driver-side validation in the future and it might become impossible to have a mismatch like this (ref: https://github.com/scylladb/scylla-rust-driver/issues/463). We would have to get rid of the test after this is implemented.
- This test should run when changes are committed to Scylla repo, not when changes are committed here. We only test with the latest released version.

Apparently, we need a framework/tools that allows to craft incorrect requests and verify that Scylla rejects them properly. Perhaps we could factor out some lower-level parts of the Python driver to allow that? cc: @Lorak-mmk

**Comment by Lorak-mmk** [comment]
Now the aforementioned validations were implemented, so it's no longer possible to craft such requests using rust driver.

However, driver is split into few crates, and scylla-cql crate is imho a very good tool for such tests. Using only scylla-cql and tokio it takes a small amount of code to create something resembling a session and sens such requests. Maybe it could be used in Scylla tests @yarongilor ?

**Comment by Lorak-mmk** [comment]
Closing this for reasons stated by me and @piodul
