### ISSUE TITLE
Serialization refactor: adjust the codebase to use `SerializeRow` and `SerializeCql` in the public API

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla-rust-driver#822]
Sub-task of https://github.com/scylladb/scylla-rust-driver/issues/801 - see the description for more details.

**Comment by Lorak-mmk** [comment]
This was mostly addressed by https://github.com/scylladb/scylla-rust-driver/pull/858 - what is missing is batch implementation.
Attempt at batches was done here by me: https://github.com/scylladb/scylla-rust-driver/pull/870 , but we decided with @piodul this is not a good API, and new PR is currently in the works by @piodul

**Comment by Lorak-mmk** [comment]
Done in https://github.com/scylladb/scylla-rust-driver/pull/858 and https://github.com/scylladb/scylla-rust-driver/pull/881
