### ISSUE TITLE
Use server events to trigger metadata refresh

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla-rust-driver#85]
We currently refresh metadata (e.g. token ring) every 10 seconds. Switch to using server events to avoid the periodic polling.

**Comment by kbr-** [comment]
I think the polling should stay too even when we handle events, but maybe it shouldn't be so often.

**Comment by psarna** [comment]
@havaker this issue is a good starting point for events. More info is in the protocol spec itself: https://github.com/apache/cassandra/blob/2d9d17894dab365df09f515e37b62b658bce6594/doc/native_protocol_v4.spec#L737
