### ISSUE TITLE
Tablet support

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla-rust-driver#867]
In the upcoming version of ScyllaDB there's a new architecture based on tablets: https://github.com/scylladb/scylladb/pull/13387

The Rust Driver should be updated to support load balancing, reading of metadata of keyspaces with tablets enabled.

See reference implementations: https://github.com/scylladb/python-driver/pull/249, https://github.com/scylladb/gocql/pull/137

**Comment by mykaul** [comment]
Well done all!
