### ISSUE TITLE
How to serialise custom types?

### ISSUE THREAD

**Issue by flaxeneel2** [scylladb/scylla-rust-driver#868]
Hi there!
I am new to scylladb, and was trying to use it to make a web app. I had a custom type `AccessLevel` that was just an enum that i wanted to store as an i32 in the db. I can just .into() it to an i32 (since i implemented Into<i32> for this enum), but, i was potentially going to store it many times, i did not want to ,into() to i32 every time, so I decided to impl Value for it, but for some reason, despite it writing 4 bytes to the buffer, it errors with "truncated frame: expected 2 bytes, length is 1". I suspect this is because the values im working with are very small (as of right now, only 1-3 items in the enum).

How can i serialise it so it works properly? The code i tried:
```rs
impl scylla::frame::value::Value for AccessLevel {
    fn serialize(&self, buf: &mut Vec<u8>) -> Result<(), ValueTooBig> {
        // TODO: Fix access level to scylla cql value serialization
        log!("Buffer size at start: {}", buf.len());
        let as_i32: i32 = (*self).into();
        for byte in as_i32.to_be_bytes() {
            buf.push(byte);
            log!("Buffer size after pushing {:x}: {}", byte, buf.len());
        }
        Ok(())
    }
}
```
The output:
```
LOG:   Buffer size at start: 134
LOG:   Buffer size after pushing 0: 135
LOG:   Buffer size after pushing 0: 136
LOG:   Buffer size after pushing 0: 137
LOG:   Buffer size after pushing 1: 138
thread 'actix-server worker 0' panicked at 'called `Result::unwrap()` on an `Err` value: DbError(ProtocolError, "truncated frame: expected 2 bytes, length is 1")', src\entities\users\user.rs:54:115
```

Does it require me to push the size or something at the very start too? Me pushing a byte with value 4 before pushing my bytes didnt work either (with a different error `truncated frame: expected 67108864 bytes, length is 3`)

EDIT:
I tried pushing the length of (4u8) after the for loop of all the bytes, and got the error `Exception while binding column access_level: marshaling error: Validation failed for type org.apache.cassandra.db.marshal.Int32Type: got 1 bytes`. Though looks like no matter what value for what im assuming as length that i push, it seems like its the same result, so i guess all im doing is fulfilling the truncated frame problem without actually addressing the problem??

Sorry about asking such questions in the issues tab. I would've loved to join the slack and ask there, but I am a student and have none of the email domains that are allowed into the slack

**Comment by mykaul** [comment]
This looks like a Rust driver issue. Shall I move the issue to that repo perhaps?

**Comment by piodul** [comment]
If you want to serialize your enum exactly as you would serialize an `i32`, you can just use the `impl Value for i32`:

```rust
// Didn't try to compile it, but if it doesn't compile then at least should present the idea
impl scylla::frame::value::Value for AccessLevel {
    fn serialize(&self, buf: &mut Vec<u8>) -> Result<(), ValueTooBig> {
        let as_i32: i32 = (*self).into();
        as_i32.serialize(buf)
    }
}
```

> Does it require me to push the size or something at the very start too?

The `Value` trait requires the pushed data to be a `[value]`, according to the [CQL protocol format](https://github.com/apache/cassandra/blob/865d7c30e4755e74c4e4d26205a7aed4cfb55710/doc/native_protocol_v4.spec). It needs to be prepended with a big-endian `i32` indicating the length of the data that follows it. In your case, you should prepend it with `[0u8, 0u8, 0u8, 4u8]` - but you don't need to care for such low-level details if you can delegate to an existing implementation.

**Comment by Lorak-mmk** [comment]
As you can see in the definition of `Value`, it requires you to serialize your value to the buffer as `[bytes]`. In the CQL specification `https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec` you can see that `[bytes]` is:
- `[bytes]` is: `A [int] n, followed by n bytes if n >= 0. If n < 0, no byte should follow and the value represented is `null`.`
- `[int]` is: `A 4 bytes integer`
- In the section 6: `As with the rest of the native protocol, all encodings are big-endian.`

So you first need to push 4-byte length of the buffer, in big endian, and then the contents.

We are currently working on serialization refactor, next version of the driver will  include it. With the new traits it will be very hard / impossible to make such mistake because provided builders will take care of serializing length.

**Comment by flaxeneel2** [comment]
Hi,
Yes thank you for your response. I just tested adding 3 more bytes of 0s to the length before the 4, looks like it worked. My code:
```rs
impl scylla::frame::value::Value for AccessLevel {
    fn serialize(&self, buf: &mut Vec<u8>) -> Result<(), ValueTooBig> {
        // TODO: Fix access level to scylla cql value serialization=

        log!("Buffer size at start: {}", buf.len());
        let as_i32: i32 = (*self).into();
        buf.push(0u8);
        buf.push(0u8);
        buf.push(0u8);
        buf.push(4u8);
        for byte in as_i32.to_be_bytes() {
            buf.push(byte);
            log!("Buffer size after pushing {:x}: {}", byte, buf.len());
        }
}
```
(The code above was just for testing purposes)
![image](https://github.com/scylladb/scylla-rust-driver/assets/60919292/23acb233-2534-453b-9dbf-15c8d25fc4b9)

It works perfectly! Thank you very much
