### ISSUE TITLE
Calculate replica sets when performing token-aware routing

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla-rust-driver#88]
Currently, when executing a prepared statement, we calculate the token of the partition key and pick the connection to the node which owns this token (i.e. which owns the token range/vnode that this token lies in).

The owner of a token should be one of the replicas for the given partition, but I'm not sure if it will always be -- maybe in NTS it could happen that this owner lies in a data-center that the keyspace does not replicate to, in which case it won't be a replica.

In any case, there can and usually will be other replicas based on the replication strategy of the keyspace that we're performing the statement on. The connection picking code should calculate this set of replicas and in case executing the statement fails on one of them, try another one. It could also try balancing the load between the replicas somehow by e.g. picking the connections in a round-robin fashion.

**Comment by piodul** [comment]
This was implemented long time ago, we have several load balancing policies implemented - including TokenAwarePolicy which - combined with RoundRobinPolicy - chooses a node from the set of replicas randomly. Closing.
