### ISSUE TITLE
Introduce attribute on `SerializeRow` to omit type/order checking

### ISSUE THREAD

**Issue by Jasperav** [scylladb/scylla-rust-driver#896]
For Catalytic the current checks which `SerializeRow` does for type checking and ordering is unnecessary. The migration guide [here](https://rust-driver.docs.scylladb.com/stable/migration-guides/0.11-serialization.html) mentions that I could switch to `SerializeCql` with some flavors to get the same result. I was wondering if these changes would come to `SerializeRow` itself as well. I don't fully understand the differences between the two traits and which one fits best for Catalytic.

It seems like `SerializeCql` is thinking my fields are all Udt (seeing the code from cargo expand) while I don't use Udts:

```
let (type_name, keyspace, field_types) = match typ {
    scylla::_macro_internal::ColumnType::UserDefinedType {
        type_name,
        keyspace,
        field_types,
        ..
    } => (type_name, keyspace, field_types),
    _ => {
        return ::std::result::Result::Err(
            mk_typck_err(
                scylla::_macro_internal::UdtTypeCheckErrorKind::NotUdt,
            ),
        );
    }
};
...
return ::std::result::Result::Err(
    mk_typck_err(scylla::_macro_internal::UdtTypeCheckErrorKind::ValueMissingForUdtField {
        field_name: <_ as ::std::string::ToString>::to_string("json"),
    }),
);
```

which makes me think that `SerializeCql` will serialize the values in a different way than `SerializeRow`.

**Comment by Lorak-mmk** [comment]
`SerializeCql` trait allows serializing as a single Cql value - it is successor to old `Value` trait. `SerializeCql` proc macro allows to serialize given struct as UDT.
See documentation for `SerializeCql` trait: https://docs.rs/scylla/latest/scylla/serialize/value/trait.SerializeCql.html
and `SerializeCql` macro: https://docs.rs/scylla-cql/latest/scylla_cql/macros/derive.SerializeCql.html

Things implementing `SerializeRow` trait can be passed as query arguments - so if `t: T` and T implements  SerializeRow, you can call session.execute(some_query, t).await;

See the documentation for `SerializeRow` trait: https://docs.rs/scylla/latest/scylla/serialize/row/trait.SerializeRow.html
and `SerializeRow` proc macro: https://docs.rs/scylla-cql/latest/scylla_cql/macros/derive.SerializeRow.html

In your case, if you want to pass given struct to session.execute etc, you want to use `SerializeRow`. If fields in your struct are in the same order as bind markers in the query, you can use `#[scylla(flavor = "enforce_order")]` attribute to skip field sorting and only check names / types.
If you want to skip name checks (and I understand it may make sense for Catalytic), which basically means that everything will behave like old `ValueList` (+ type checks), you can also use `#[scylla(skip_name_checks)]` attribute.

Skipping type checks can't be done for now - for a value to be serialized it needs to know the type to be serialized to. Overhead of this checking should be negligible. If, in the future, we decided to make it somehow possible, I'd recommend against that, even in ORM use case, to avoid the possibility of data corruption.

**Comment by Jasperav** [comment]
@Lorak-mmk Thanks, it make more sense now. I will convert using `SerializeRow` with the attributes.

**Comment by Jasperav** [comment]
Maybe an idea to open 'Discussions' on this crate :) then I can ask it there instead of opening issues.

**Comment by mykaul** [comment]
We use https://forum.scylladb.com/ or Slack , I'm not sure another venue for discussions is needed.

**Comment by nyh** [comment]
> We use https://forum.scylladb.com/ or Slack , I'm not sure another venue for discussions is needed.

Note that this is the scylla-rust-driver repository, not the main scylla core, so it's not clear how a user can guess to go to forum.scylladb.com. The README (https://github.com/scylladb/scylla-rust-driver) does clearly ask to use Slack though - so if you think they should also use the forum, please mention that too.

I think pointing people **only** to Slack is a mistake, although it admit it should be left to the driver developers to decide what communication methods they prefer and my opinion on the matter is less important. But if you want my opinion, it is that Slack - an instant-messaging tool - isn't a good tool for an asynchronous discussion (where a user asks a question but the developer is busy working on other stuff, or on vacation, and will only have time to answer it a couple of days later).
