### ISSUE TITLE
SerializeCql is a confusing name for a macro

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/scylla-rust-driver#905]
As evidenced by https://github.com/scylladb/scylla-rust-driver/issues/896 , `SerializeCql` is a confusing name for a macro that allows serializing UDT. It should be called `SerializeUDT`.

**Comment by piodul** [comment]
It is very common for derive macros to have exactly the same name as the trait they implement. To me at least, it's confusing when you write `#[derive(SerializeUdt)]` while there is no corresponding `SerializeUdt` trait.

Perhaps we could change both the trait and macro name to `SerializeValue` instead - that way it will be clear that it's about serializing values and not rows.

**Comment by Lorak-mmk** [comment]
I tried to get the right documentation to render in `scylla` without moving the comments, without success. No combination of `#[doc(inline)]`, `#[doc(no_inline)]` and changing exports (e.g. importing SerializeRow / SerializeCql directly apart from the wildcard import) did the trick.

Do we need those examples to compile? We have other tests for those macros, so imo the easiest solution is to move the docs to scylla_macros crate and mark examples as `ignore`. This would get rid of another problem that I don't think can be solved differently: even in scylla_cql crate, the placeholder comment from scylla_macros is appended to docs. So the end of SerializeCql docs is currently:
```
#[scylla(rename = "name_in_the_udt")]

Serializes the field to the UDT struct field with given name instead of its Rust name. See the documentation for this item in the scylla crate.
```

Note the last sentence, that should not be there.

**Comment by wprzytula** [comment]
With @Lorak-mmk, we prefer the name change of both the trait and the derive macro to `SerializeValue`. We need to remember to rename the upcoming `DeserializeCql` to `DeserializeValue` as well.
