### ISSUE TITLE
query_paged is a misleading name

### ISSUE THREAD

**Issue by Lorak-mmk** [scylladb/scylla-rust-driver#940]
`query_paged` suggests that the executed query will be paged, while this is not the case.
Whether the query is paged or not is controlled by querie's `page_size` attribute.
The only difference between query and query_paged is that the former accepts custom paging_state, so something like `query_with_paging_state` would probably be a better name.

**Comment by roydahan** [comment]
@wprzytula I see this one is in "High Priority" but it doesn't have a milestone.
Is it planned to pre-1.0 milestones?
