### ISSUE TITLE
Deserialization refactor: macros for the new traits

### ISSUE THREAD

**Issue by wprzytula** [scylladb/scylla-rust-driver#962]
Sub-task of https://github.com/scylladb/scylla-rust-driver/issues/961.

The new `DeserializeRow` and `DeserializeCql` traits will need to have their corresponding procedural macros implemented.

**Comment by Lorak-mmk** [comment]
Note: It would be good to support `#[scylla(skip)]` attribute (currently used by serialization macros). We could either require the field to implement `Default` or provide default value in attribute (I think first option makes more sens).

Example use case: https://forum.scylladb.com/t/how-to-ignore-field-in-rust-struct/1419
