### ISSUE TITLE
Multiple create statement support. 

### ISSUE THREAD

**Issue by siddharthteli12** [scylladb/scylla-rust-driver#981]
Currently , Creating multiple tables look like this-  

```
   session.query("CREATE TABLE IF NOT EXISTS test (user_id text primary key)",&[],) .await?;
   session.query("CREATE TABLE IF NOT EXISTS test2 (user_id text primary key)",&[],) .await?;
   session.query("CREATE TABLE IF NOT EXISTS test3 (user_id text primary key)",&[],) .await?;
```

- Is their any alternative way where we can batch multiple create statement together and execute it once.  
- Or is it insignificant to have batching for **create query** because they are rare and max occurrence can be in hundreds. So wouldn't lead to any performance improvement?

**Comment by piodul** [comment]
The driver supports sending batches of statements. Did you try it?
https://docs.rs/scylla/latest/scylla/transport/session/struct.Session.html#method.batch
I'm also not sure if it is supported scylla-side, but you should give it a shot.

**Comment by siddharthteli12** [comment]
Thanks for your reply @piodul and @Lorak-mmk  , As per [document](https://docs.rs/scylla/latest/scylla/transport/session/struct.Session.html#method.batch), batch only supports INSERT, UPDATE and DELETE. I also tested it from my side DDL statements cannot be batched.
